********************************************************************************

* This syntax routine lifts all records indicating a productcode for an antidepressant from the CPRD therapy files across old and new data deliveries and saves these as a separate dataset using VNS's updated codelist ready for cleaning

* Author: Flo Martin (adapted from scripts by Hein Heuvelman)

* Date: 26/06/2023

********************************************************************************

* Datasets generated by this do-file

	* The antidepressant prescription events in All_Therapy identified using the antidpressant codelist (checked by VNM) for cleaning and hot-decking found in the temporary data directory (3_tempdata)
	
	* $Tempdatadir\AD_pxn_events_from_All_Therapy.dta

********************************************************************************

* Start logging

	log using "$Logdir\3_exposure\1_identifying ad prescriptions.txt", replace
	
********************************************************************************
	
* Identify the antidepressant prescriptions in each block of data and then merge these as All_Therapy is too large and causes Stata to crash	
	
	forvalues x=0/11 {

		use "$Datadir\formatted_cprd_data\Therapy_`x'.dta", clear
		count
		merge m:1 prodcode using "$Codesdir\antidepressants_codelist.dta", keep(3) nogen
		compress
		save "$Tempdatadir\AD_pxn_events_in_Therapy_`x'.dta", replace
		
	}
	
* Append the antidepressant prescriptions from each chunk ready to de-duplicate and use in ananlyses moving forward
	
	use "$Tempdatadir\AD_pxn_events_in_Therapy_0.dta"
	
	forvalues x=1/11 {
		
		append using "$Tempdatadir\AD_pxn_events_in_Therapy_`x'.dta"
		
	}
	
	count
	duplicates drop
	count // 40,690,019 prescriptions for antidepressants
	
	save "$Tempdatadir\AD_pxn_events_from_All_Therapy.dta", replace
	
********************************************************************************

* Stop logging

	log close
	
********************************************************************************
