********************************************************************************

* Generating a parity variable having removed conflicting and historical pregnancies

* Author: Flo Martin

* Date: 03/11/2022

********************************************************************************

* Datasets generated by this do-file

* 		- $Datadir\covariates\new_parity.dta

********************************************************************************

	* Parity - now use live birth to define parity (number of children)

	use "$Datadir\derived_data\pregreg_conflict_hist_rm.dta", clear 
	keep patid pregid updated_outcome pregnum_new pregstart_num
	
	tab updated_outcome
	tab updated_outcome, nol
	keep if updated_outcome==1 | updated_outcome==2 | updated_outcome==3 | updated_outcome==11 | updated_outcome==12
	
	sort patid pregstart_num
	bysort patid: egen parity=seq(), f(0)
	summ parity
	
	tab parity
	label variable parity"Parity at the start of pregnancy"
	
	merge 1:1 patid pregid using "$Datadir\derived_data\pregreg_conflict_hist_rm.dta"
	keep patid pregid updated_outcome parity pregnum_new
	
	count
	
	drop if patid==. | pregid==.
	drop if updated_outcome==.
	sort patid pregid pregnum_new // for pregnancy losses parity isn't carried forward - need to apply the same method as for gravidity history to parity
	
	reshape wide pregid parity updated_outcome, i(patid) j(pregnum_new)
	
	gen parity23=.
	gen pregid23=.
	gen updated_outcome23=.
	
	replace parity1 = 0
	
	forvalues x=2/23 {
		
		local y=`x'-1
		
		replace parity`x' = parity`y' if updated_outcome`x'!=. & inlist(updated_outcome`y', 4,5,6,7,8,9,10,13)
		replace parity`x' = parity`y' if parity`x'==. & updated_outcome`x'!=.
		replace parity`x' = parity`y' + 1 if inlist(updated_outcome`y', 1,2,3,11,12) & updated_outcome`x'!=.
		
	}
	
	/*
	replace parity2 = parity1 if updated_outcome2!=. & inlist(updated_outcome1, 4,5,6,7,8,9,10,13)
	replace parity2 = parity1 if parity2==. & updated_outcome2!=.
	replace parity2 = parity1 + 1 if inlist(updated_outcome1, 1,2,3,11,12) & updated_outcome2!=.
	
	replace parity3 = parity2 if updated_outcome3!=. & inlist(updated_outcome2, 4,5,6,7,8,9,10,13)
	replace parity3 = parity2 if parity3==. & updated_outcome3!=.
	replace parity3 = parity2 + 1 if inlist(updated_outcome2, 1,2,3,11,12) & updated_outcome3!=.
	
	replace parity4 = parity3 if updated_outcome4!=. & inlist(updated_outcome3, 4,5,6,7,8,9,10,13)
	replace parity4 = parity3 if parity4==. & updated_outcome4!=.
	replace parity4 = parity3 + 1 if inlist(updated_outcome3, 1,2,3,11,12) & updated_outcome4!=.
	
	replace parity5 = parity4 if updated_outcome5!=. & inlist(updated_outcome4, 4,5,6,7,8,9,10,13)
	replace parity5 = parity4 if parity5==. & updated_outcome5!=.
	replace parity5 = parity4 + 1 if inlist(updated_outcome4, 1,2,3,11,12) & updated_outcome5!=.
	
	replace parity6 = parity5 if updated_outcome6!=. & inlist(updated_outcome5, 4,5,6,7,8,9,10,13)
	replace parity6 = parity5 if parity6==. & updated_outcome6!=.
	replace parity6 = parity5 + 1 if inlist(updated_outcome5, 1,2,3,11,12) & updated_outcome6!=.
	
	replace parity7 = parity6 if updated_outcome7!=. & inlist(updated_outcome6, 4,5,6,7,8,9,10,13)
	replace parity7 = parity6 if parity7==. & updated_outcome7!=.
	replace parity7 = parity6 + 1 if inlist(updated_outcome6, 1,2,3,11,12) & updated_outcome7!=.
	
	replace parity8 = parity7 if updated_outcome8!=. & inlist(updated_outcome7, 4,5,6,7,8,9,10,13)
	replace parity8 = parity7 if parity8==. & updated_outcome8!=.
	replace parity8 = parity7 + 1 if inlist(updated_outcome7, 1,2,3,11,12) & updated_outcome8!=.
	
	replace parity9 = parity8 if updated_outcome9!=. & inlist(updated_outcome8, 4,5,6,7,8,9,10,13)
	replace parity9 = parity8 if parity9==. & updated_outcome9!=.
	replace parity9 = parity8 + 1 if inlist(updated_outcome8, 1,2,3,11,12) & updated_outcome9!=.
	
	replace parity10 = parity9 if updated_outcome10!=. & inlist(updated_outcome9, 4,5,6,7,8,9,10,13)
	replace parity10 = parity9 if parity10==. & updated_outcome10!=.
	replace parity10 = parity9 + 1 if inlist(updated_outcome9, 1,2,3,11,12) & updated_outcome10!=.
	
	replace parity11 = parity10 if updated_outcome11!=. & inlist(updated_outcome10, 4,5,6,7,8,9,10,13)
	replace parity11 = parity10 if parity11==. & updated_outcome11!=.
	replace parity11 = parity10 + 1 if inlist(updated_outcome10, 1,2,3,11,12) & updated_outcome11!=.
	
	replace parity12 = parity11 if updated_outcome12!=. & inlist(updated_outcome11, 4,5,6,7,8,9,10,13)
	replace parity12 = parity11 if parity12==. & updated_outcome12!=.
	replace parity12 = parity11 + 1 if inlist(updated_outcome11, 1,2,3,11,12) & updated_outcome12!=.
	
	replace parity13 = parity12 if updated_outcome13!=. & inlist(updated_outcome12, 4,5,6,7,8,9,10,13)
	replace parity13 = parity12 if parity13==. & updated_outcome13!=.
	replace parity13 = parity12 + 1 if inlist(updated_outcome12, 1,2,3,11,12) & updated_outcome13!=.
	
	replace parity14 = parity13 if updated_outcome14!=. & inlist(updated_outcome13, 4,5,6,7,8,9,10,13)
	replace parity14 = parity13 if parity14==. & updated_outcome14!=.
	replace parity14 = parity13 + 1 if inlist(updated_outcome13, 1,2,3,11,12) & updated_outcome14!=.
	
	replace parity15 = parity14 if updated_outcome15!=. & inlist(updated_outcome14, 4,5,6,7,8,9,10,13)
	replace parity15 = parity14 if parity15==. & updated_outcome15!=.
	replace parity15 = parity14 + 1 if inlist(updated_outcome14, 1,2,3,11,12) & updated_outcome15!=.
	
	replace parity16 = parity15 if updated_outcome16!=. & inlist(updated_outcome15, 4,5,6,7,8,9,10,13)
	replace parity16 = parity15 if parity16==. & updated_outcome16!=.
	replace parity16 = parity15 + 1 if inlist(updated_outcome15, 1,2,3,11,12) & updated_outcome16!=.
	
	replace parity17 = parity16 if updated_outcome17!=. & inlist(updated_outcome16, 4,5,6,7,8,9,10,13)
	replace parity17 = parity16 if parity17==. & updated_outcome17!=.
	replace parity17 = parity16 + 1 if inlist(updated_outcome16, 1,2,3,11,12) & updated_outcome17!=.
	
	replace parity18 = parity17 if updated_outcome18!=. & inlist(updated_outcome17, 4,5,6,7,8,9,10,13)
	replace parity18 = parity17 if parity18==. & updated_outcome18!=.
	replace parity18 = parity17 + 1 if inlist(updated_outcome17, 1,2,3,11,12) & updated_outcome18!=.
	
	replace parity19 = parity18 if updated_outcome19!=. & inlist(updated_outcome18, 4,5,6,7,8,9,10,13)
	replace parity19 = parity18 if parity19==. & updated_outcome19!=.
	replace parity19 = parity18 + 1 if inlist(updated_outcome18, 1,2,3,11,12) & updated_outcome19!=.
	
	replace parity20 = parity19 if updated_outcome20!=. & inlist(updated_outcome19, 4,5,6,7,8,9,10,13)
	replace parity20 = parity19 if parity20==. & updated_outcome20!=.
	replace parity20 = parity19 + 1 if inlist(updated_outcome19, 1,2,3,11,12) & updated_outcome20!=.
	
	replace parity21 = parity20 if updated_outcome21!=. & inlist(updated_outcome20, 4,5,6,7,8,9,10,13)
	replace parity21 = parity20 if parity21==. & updated_outcome21!=.
	replace parity21 = parity20 + 1 if inlist(updated_outcome20, 1,2,3,11,12) & updated_outcome21!=.
	
	*/
	
	reshape long pregid updated_outcome parity, i(patid) j(pregnum_new)
	drop if pregid==.
	count
	
	tab parity, m
	
	summ parity
	
	gen parity_cat = 0 if parity==0
	replace parity_cat = 1 if parity==1
	replace parity_cat = 2 if parity==2
	replace parity_cat = 3 if parity>=3 & parity!=.
	
	label define parity_lb 1"1" 2"2" 3"3+"
	label values parity_cat parity_lb
	
	tab parity_cat, m
	
	keep patid pregid parity parity_cat
	order patid pregid parity parity_cat
	
	save "$Datadir\covariates\new_parity.dta", replace
	
********************************************************************************
