********************************************************************************

* This syntax routine pulls together all the pieces of Therapy data provided by CPRD in the new data delivery ready for using with the old Therapy data delivery

* Author: Flo Martin (adapted from scripts by Hein Heuvelman)

* Date: 26/06/2023

********************************************************************************

* Datasets generated by this do-file

	* 12 chunks of Therapy data for using in subsequent PhD projects
	
	* $Tempdatadir\Therapy_0.dta - $Tempdatadir\Therapy_11.dta

********************************************************************************

* Start logging

	log using "$Logdir\1_formatting\11_formatting therapy.txt", replace
	
********************************************************************************

* Dataset 0

	use "$Rawdatadir\redelivery may 23\primary care\Therapy_01_0.dta", clear
	
	foreach x in 02 03 04 05 06 07 08 09 10 11 12 13 {	
		
		append using "$Rawdatadir\redelivery may 23\primary care\Therapy_`x'_0.dta"
		
	}
	
	* Data management
			
	gen eventdate_num = date(eventdate, "DMY")
	format eventdate_num %td
		
	* Label variables
			
	label variable patid "Patient ID"
	label variable eventdate "Date of therapy event - string"
	label variable eventdate_num "Date of therapy event - numerical"
	label variable consid "Consultation ID: linkage with consultation file when used with pracid"
	label variable prodcode "CPRD code for treatment, selected by GP"
	label variable staffid "ID of staff entering data onto Vision, zero ==unknown"
	label variable dosageid "dosage ID: linkage with dosage info when used with pracid and eventtype therapy"
	label variable bnfcode "Chapter and section of British National Formulary pharmaceutical reference book"
	label variable qty "Total quantity entered by GP for prescribed product"
	label variable numdays "Number of treatment days prescribed for therapy event"
	label variable numpacks "Number of product packs prescribed for therapy event"
	label variable packtype "Pack size or type of prescribed product"
	label variable issueseq "Prescription part of repeat schedule"
				
	* Sort on patient ID and eventdate
			
	sort patid eventdate_num
				
	* Compress data
		
	compress *
	
	save "$Datadir\formatted_cprd_data\Therapy_0.dta", replace
	
* Datasets 1, 2, 3, 4, 5, & 7
	
	foreach y in 1 2 3 4 5 7  {
	
		use "$Rawdatadir\redelivery may 23\primary care\Therapy_01_`y'.dta", clear
		
		foreach x in 02 03 04 05 06 07 08 09 10 11 12 13 14 {	
			
			append using "$Rawdatadir\redelivery may 23\primary care\Therapy_`x'_`y'.dta"
			
		}
		
		* Data management
			
		gen eventdate_num = date(eventdate, "DMY")
		format eventdate_num %td
			
		* Label variables
				
		label variable patid "Patient ID"
		label variable eventdate "Date of therapy event - string"
		label variable eventdate_num "Date of therapy event - numerical"
		label variable consid "Consultation ID: linkage with consultation file when used with pracid"
		label variable prodcode "CPRD code for treatment, selected by GP"
		label variable staffid "ID of staff entering data onto Vision, zero ==unknown"
		label variable dosageid "dosage ID: linkage with dosage info when used with pracid and eventtype therapy"
		label variable bnfcode "Chapter and section of British National Formulary pharmaceutical reference book"
		label variable qty "Total quantity entered by GP for prescribed product"
		label variable numdays "Number of treatment days prescribed for therapy event"
		label variable numpacks "Number of product packs prescribed for therapy event"
		label variable packtype "Pack size or type of prescribed product"
		label variable issueseq "Prescription part of repeat schedule"
					
		* Sort on patient ID and eventdate
				
		sort patid eventdate_num
					
		* Compress data
			
		compress *
		
		save "$Datadir\formatted_cprd_data\Therapy_`y'.dta", replace
	
	}
	
* Dataset 6
	
	foreach y in 6 {
	
		use "$Rawdatadir\redelivery may 23\primary care\Therapy_01_`y'.dta", clear
		
		foreach x in 02 03 04 05 06 07 08 09 10 11 12 13 14 15 {	
			
			append using "$Rawdatadir\redelivery may 23\primary care\Therapy_`x'_`y'.dta"
			
		}
		
		* Data management
			
		gen eventdate_num = date(eventdate, "DMY")
		format eventdate_num %td
			
		* Label variables
				
		label variable patid "Patient ID"
		label variable eventdate "Date of therapy event - string"
		label variable eventdate_num "Date of therapy event - numerical"
		label variable consid "Consultation ID: linkage with consultation file when used with pracid"
		label variable prodcode "CPRD code for treatment, selected by GP"
		label variable staffid "ID of staff entering data onto Vision, zero ==unknown"
		label variable dosageid "dosage ID: linkage with dosage info when used with pracid and eventtype therapy"
		label variable bnfcode "Chapter and section of British National Formulary pharmaceutical reference book"
		label variable qty "Total quantity entered by GP for prescribed product"
		label variable numdays "Number of treatment days prescribed for therapy event"
		label variable numpacks "Number of product packs prescribed for therapy event"
		label variable packtype "Pack size or type of prescribed product"
		label variable issueseq "Prescription part of repeat schedule"
					
		* Sort on patient ID and eventdate
				
		sort patid eventdate_num
					
		* Compress data
			
		compress *
	
		save "$Datadir\formatted_cprd_data\Therapy_`y'.dta", replace
	
	}

* Dataset 8
	
	foreach y in 8 {
	
		use "$Rawdatadir\redelivery may 23\primary care\Therapy_01_`y'.dta", clear
		
		foreach x in 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 {	
			
			append using "$Rawdatadir\redelivery may 23\primary care\Therapy_`x'_`y'.dta"
			
		}
		
		* Data management
			
		gen eventdate_num = date(eventdate, "DMY")
		format eventdate_num %td
			
		* Label variables
				
		label variable patid "Patient ID"
		label variable eventdate "Date of therapy event - string"
		label variable eventdate_num "Date of therapy event - numerical"
		label variable consid "Consultation ID: linkage with consultation file when used with pracid"
		label variable prodcode "CPRD code for treatment, selected by GP"
		label variable staffid "ID of staff entering data onto Vision, zero ==unknown"
		label variable dosageid "dosage ID: linkage with dosage info when used with pracid and eventtype therapy"
		label variable bnfcode "Chapter and section of British National Formulary pharmaceutical reference book"
		label variable qty "Total quantity entered by GP for prescribed product"
		label variable numdays "Number of treatment days prescribed for therapy event"
		label variable numpacks "Number of product packs prescribed for therapy event"
		label variable packtype "Pack size or type of prescribed product"
		label variable issueseq "Prescription part of repeat schedule"
					
		* Sort on patient ID and eventdate
				
		sort patid eventdate_num
					
		* Compress data
			
		compress *
		
		save "$Datadir\formatted_cprd_data\Therapy_`y'.dta", replace
		
	}
		
* Dataset 10		
		
	foreach y in 10 {
	
		use "$Rawdatadir\redelivery may 23\primary care\Therapy_01_`y'.dta", clear
		
		foreach x in 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 {	
			
			append using "$Rawdatadir\redelivery may 23\primary care\Therapy_`x'_`y'.dta"
			
		}
		
		* Data management
			
		gen eventdate_num = date(eventdate, "DMY")
		format eventdate_num %td
			
		* Label variables
				
		label variable patid "Patient ID"
		label variable eventdate "Date of therapy event - string"
		label variable eventdate_num "Date of therapy event - numerical"
		label variable consid "Consultation ID: linkage with consultation file when used with pracid"
		label variable prodcode "CPRD code for treatment, selected by GP"
		label variable staffid "ID of staff entering data onto Vision, zero ==unknown"
		label variable dosageid "dosage ID: linkage with dosage info when used with pracid and eventtype therapy"
		label variable bnfcode "Chapter and section of British National Formulary pharmaceutical reference book"
		label variable qty "Total quantity entered by GP for prescribed product"
		label variable numdays "Number of treatment days prescribed for therapy event"
		label variable numpacks "Number of product packs prescribed for therapy event"
		label variable packtype "Pack size or type of prescribed product"
		label variable issueseq "Prescription part of repeat schedule"
					
		* Sort on patient ID and eventdate
				
		sort patid eventdate_num
					
		* Compress data
			
		compress *
	
		save "$Datadir\formatted_cprd_data\Therapy_`y'.dta", replace
	
	}
	
	foreach y in 9 {
	
		use "$Rawdatadir\redelivery may 23\primary care\Therapy_01_`y'.dta", clear
		
		foreach x in 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 {	
			
			append using "$Rawdatadir\redelivery may 23\primary care\Therapy_`x'_`y'.dta"
			
		}
		
		* Data management
			
		gen eventdate_num = date(eventdate, "DMY")
		format eventdate_num %td
			
		* Label variables
				
		label variable patid "Patient ID"
		label variable eventdate "Date of therapy event - string"
		label variable eventdate_num "Date of therapy event - numerical"
		label variable consid "Consultation ID: linkage with consultation file when used with pracid"
		label variable prodcode "CPRD code for treatment, selected by GP"
		label variable staffid "ID of staff entering data onto Vision, zero ==unknown"
		label variable dosageid "dosage ID: linkage with dosage info when used with pracid and eventtype therapy"
		label variable bnfcode "Chapter and section of British National Formulary pharmaceutical reference book"
		label variable qty "Total quantity entered by GP for prescribed product"
		label variable numdays "Number of treatment days prescribed for therapy event"
		label variable numpacks "Number of product packs prescribed for therapy event"
		label variable packtype "Pack size or type of prescribed product"
		label variable issueseq "Prescription part of repeat schedule"
					
		* Sort on patient ID and eventdate
				
		sort patid eventdate_num
					
		* Compress data
			
		compress *
		
		save "$Datadir\formatted_cprd_data\Therapy_`y'.dta", replace
	
	}
	
* Old Therapy

	use "$Cohortonedir\formatted_cprd_data\All_Therapy.dta", clear
	
	drop sysdate sysdate_num drugdmd prn
	
	sort patid eventdate_num
	
	save "$Datadir\formatted_cprd_data\Therapy_11.dta", replace
	
* Append all therapy files together 

	use "$Datadir\formatted_cprd_data\Therapy_0.dta", clear
	
	forvalues x=1/11 {
		
		append using "$Datadir\formatted_cprd_data\Therapy_`x'.dta"
		
	}
	
	count
	
	save "$Datadir\formatted_cprd_data\All_Therapy.dta", replace
	
	keep patid eventdate eventdate_num prodcode
	
	save "$Datadir\formatted_cprd_data\All_Therapy_reduced.dta", replace
	
********************************************************************************

* Stop logging
	
	log close
	
********************************************************************************
