********************************************************************************

* Convert CPRD data to tabdelimited & stata datasets from originaldata to rawdata for cleaning

* Author: Flo Martin

* Date: 15\10\2021

********************************************************************************

* Datasets generated by this do-file

	* All raw datasets, medical/product dictionaries & the Pregnancy Register in .dta and .txt form found in the raw data directory (2_rawdata)

********************************************************************************

* Start logging
	
	log using "$Logdir\1_formatting\1_converting text files to stata files.txt", replace
	
********************************************************************************

* Save lookup files as .dta files

	cd "$Originaldir\lookups"
	
	import delimited "medical.txt", clear
	export delimited "$Lookupsdir\tabdelimited\medical.txt", replace
	save "$Lookupsdir\stata\medical.dta", replace
	
	import delimited "product.txt", clear
	export delimited "$Lookupsdir\tabdelimited\product.txt", replace
	save "$Lookupsdir\stata\product.dta", replace
	
	import delimited "entity.txt", clear
	export delimited "$Lookupsdir\tabdelimited\entity.txt", replace
	save "$Lookupsdir\stata\entity.dta", replace
	
	import delimited "TXTFILES\MAR.txt", clear
	export delimited "$Lookupsdir\tabdelimited\MAR.txt", replace
	save "$Lookupsdir\stata\MAR.dta", replace
	
	import delimited "TXTFILES\PRG.txt", clear
	export delimited "$Lookupsdir\tabdelimited\PRG.txt", replace
	save "$Lookupsdir\stata\PRG.dta", replace

********************************************************************************

* Save IMD file in rawdata

	* September 2021 delivery

	cd "$Originaldir\linkage"
	
	import delimited "practice_imd_21_000362_request2_redelivery.txt", clear
	export delimited "$Rawdatadir\original sept 21\linkage\tabdelimited\imd.txt", replace
	save "$Rawdatadir\original sept 21\linkage\stata\imd.dta", replace	
	
	* May 2023 delivery
	
	cd "$Originaldir\redelivery\linkage"
	
	import delimited "practice_imd_21_000362_delivery2.txt", clear
	export delimited "$Rawdatadir\redelivery may 23\linkage\tabdelimited\imd_23.txt", replace 
	save "$Rawdatadir\redelivery may 23\linkage\stata\imd_23.dta", replace 
	
********************************************************************************
	
* Save CPRD Pregnancy Register in rawdata folder

	* September 2021 delivery

	cd "$Originaldir\linkage"
	
	import delimited "Pregnancy_register_21_000362_request2_redelivery.txt", clear
	export delimited "$Rawdatadir\original sept 21\linkage\tabdelimited\pregnancyregister.txt", replace
	save "$Rawdatadir\original sept 21\linkage\stata\pregnancyregister.dta", replace
	
	* May 2023 delivery
	
	cd "$Originaldir\redelivery\linkage"
	
	import delimited "pregnancy_register_21_000362_delivery2_DM.txt", clear
	export delimited "$Rawdatadir\redelivery may 23\linkage\tabdelimited\pregnancyregister_23.txt", replace 
	save "$Rawdatadir\redelivery may 23\linkage\stata\pregnancyregister_23.dta", replace 
	
	* February 2024 delivery
	
	cd "$Originaldir\redelivery\feb 24"
	
	import delimited "pregnancy_register_21_000362_DM.txt", clear
	export delimited "$Rawdatadir\redelivery feb 24\tabdelimited\pregnancyregister_24.txt", replace 
	save "$Rawdatadir\redelivery feb 24\stata\pregnancyregister_24.dta", replace 
	
********************************************************************************

* Save CPRD Mother Baby Link in rawdata folder

	* September 2021 delivery

	cd "$Originaldir\linkage"
	
	import delimited "MBL_Baby_21_000362_request2_redelivery.txt", clear
	export delimited "$Rawdatadir\original sept 21\linkage\tabdelimited\mbl_baby.txt", replace
	save "$Rawdatadir\original sept 21\linkage\stata\mbl_baby.dta", replace
	
	import delimited "MBL_Mum_21_000362_request2_redelivery.txt", clear
	export delimited "$Rawdatadir\original sept 21\linkage\tabdelimited\mbl_mum.txt", replace
	save "$Rawdatadir\original sept 21\linkage\stata\mbl_mum.dta", replace
	
	* May 2023 delivery
	
	cd "$Originaldir\redelivery\linkage"
	
	import delimited "MBL_Baby_21_000362_delivery2_DM.txt", clear
	export delimited "$Rawdatadir\redelivery may 23\linkage\tabdelimited\mbl_baby_23.txt", replace 
	save "$Rawdatadir\redelivery may 23\linkage\stata\mbl_baby_23.dta", replace
	
	import delimited "MBL_Mum_21_000362_delivery2_DM.txt", clear
	export delimited "$Rawdatadir\redelivery may 23\linkage\tabdelimited\mbl_mum_23.txt", replace 
	save "$Rawdatadir\redelivery may 23\linkage\stata\mbl_mum_23.dta", replace 

********************************************************************************

* Save linkage eligibility in rawdata folder

	* September 2021 delivery

	cd "$Originaldir\linkage"
	
	import delimited "21_000362_request2_redelivery_linkage_eligibility_gold.txt", clear
	export delimited "$Rawdatadir\original sept 21\linkage\tabdelimited\linkage_eligibility.txt", replace
	save "$Rawdatadir\original sept 21\linkage\stata\linkage_eligibility.dta", replace
	
	* May 2023 delivery
	
	cd "$Originaldir\redelivery\linkage"
	
	import delimited "21_000362_delivery2_linkage_eligibility_gold.txt", clear
	export delimited "$Rawdatadir\redelivery may 23\linkage\tabdelimited\linkage_eligibility_23.txt", replace 
	save "$Rawdatadir\redelivery may 23\linkage\stata\linkage_eligibility_23.dta", replace 
	
********************************************************************************

* Save HES maternity in rawdata folder

	* September 2021 delivery

	cd "$Originaldir\linkage"
	
	import delimited "hes_maternity_21_000362_request2_redelivery.txt", clear
	export delimited "$Rawdatadir\original sept 21\linkage\tabdelimited\hes_maternity.txt", replace
	save "$Rawdatadir\original sept 21\linkage\stata\hes_maternity.dta", replace
	
	* May 2023 delivery
	
	cd "$Originaldir\redelivery\linkage"
	
	import delimited "hes_maternity_21_000362_delivery2_DM.txt", clear
	export delimited "$Rawdatadir\redelivery may 23\linkage\tabdelimited\hes_maternity_23.txt", replace 
	save "$Rawdatadir\redelivery may 23\linkage\stata\hes_maternity_23.dta", replace 
	
********************************************************************************

* Save HES diagnosis epi in rawdata folder

	* September 2021 delivery

	cd "$Originaldir\linkage"
	
	import delimited "hes_diagnosis_epi_21_000362_request2_redelivery.txt", clear
	export delimited "$Rawdatadir\original sept 21\linkage\tabdelimited\hes_diagnosis_epi.txt", replace
	save "$Rawdatadir\original sept 21\linkage\stata\hes_diagnosis_epi.dta", replace
	
	* May 2023 delivery
	
	cd "$Originaldir\redelivery\linkage"
	
	import delimited "hes_diagnosis_epi_21_000362_delivery2_DM.txt", clear
	export delimited "$Rawdatadir\redelivery may 23\linkage\tabdelimited\hes_diagnosis_epi_23.txt", replace 
	save "$Rawdatadir\redelivery may 23\linkage\stata\hes_diagnosis_epi_23.dta", replace
	
********************************************************************************

* Save HES diagnosis hosp in rawdata folder

	* September 2021 delivery

	cd "$Originaldir\linkage"
	
	import delimited "hes_diagnosis_hosp_21_000362_request2_redelivery.txt", clear
	export delimited "$Rawdatadir\original sept 21\linkage\tabdelimited\hes_diagnosis_hosp.txt", replace
	save "$Rawdatadir\original sept 21\linkage\stata\hes_diagnosis_hosp.dta", replace
	
	* May 2023 delivery
	
	cd "$Originaldir\redelivery\linkage"
	
	import delimited "hes_diagnosis_hosp_21_000362_delivery2_DM.txt", clear
	export delimited "$Rawdatadir\redelivery may 23\linkage\tabdelimited\hes_diagnosis_hosp_23.txt", replace 
	save "$Rawdatadir\redelivery may 23\linkage\stata\hes_diagnosis_hosp_23.dta", replace
	
********************************************************************************

* Save HES episodes in rawdata folder

	* September 2021 delivery

	cd "$Originaldir\linkage"
	
	import delimited "hes_episodes_21_000362_request2_redelivery.txt", clear
	export delimited "$Rawdatadir\original sept 21\linkage\tabdelimited\hes_episodes.txt", replace
	save "$Rawdatadir\original sept 21\linkage\stata\hes_episodes.dta", replace
	
	* May 2023 delivery
	
	cd "$Originaldir\redelivery\linkage"
	
	import delimited "hes_episodes_21_000362_delivery2_DM.txt", clear
	export delimited "$Rawdatadir\redelivery may 23\linkage\tabdelimited\hes_episodes_23.txt", replace 
	save "$Rawdatadir\redelivery may 23\linkage\stata\hes_episodes_23.dta", replace
	
********************************************************************************

* Save HES hospitalisations in rawdata folder

	* September 2021 delivery

	cd "$Originaldir\linkage"
	
	import delimited "hes_hospital_21_000362_request2_redelivery.txt", clear
	export delimited "$Rawdatadir\original sept 21\linkage\tabdelimited\hes_hospital.txt", replace
	save "$Rawdatadir\original sept 21\linkage\stata\hes_hospital.dta", replace
	
	* May 2023 delivery
	
	cd "$Originaldir\redelivery\linkage"
	
	import delimited "hes_hospital_21_000362_delivery2_DM.txt", clear
	export delimited "$Rawdatadir\redelivery may 23\linkage\tabdelimited\hes_hospital_23.txt", replace 
	save "$Rawdatadir\redelivery may 23\linkage\stata\hes_hospital_23.dta", replace
	
********************************************************************************

* Save HES patient in rawdata folder

	* September 2021 delivery

	cd "$Originaldir\linkage"
	
	import delimited "hes_patient_21_000362_request2_redelivery.txt", clear
	export delimited "$Rawdatadir\original sept 21\linkage\tabdelimited\hes_patient.txt", replace
	save "$Rawdatadir\original sept 21\linkage\stata\hes_patient.dta", replace
	
	* May 2023 delivery
	
	cd "$Originaldir\redelivery\linkage"
	
	import delimited "hes_patient_21_000362_delivery2_DM.txt", clear
	export delimited "$Rawdatadir\redelivery may 23\linkage\tabdelimited\hes_patient_23.txt", replace 
	save "$Rawdatadir\redelivery may 23\linkage\stata\hes_patient_23.dta", replace
	
********************************************************************************

* Save HES procedures in rawdata folder

	* September 2021 delivery

	cd "$Originaldir\linkage"
	
	import delimited "hes_procedures_epi_21_000362_request2_redelivery.txt", clear
	export delimited "$Rawdatadir\original sept 21\linkage\tabdelimited\hes_procedures.txt", replace
	save "$Rawdatadir\original sept 21\linkage\stata\hes_procedures.dta", replace
	
	* May 2023 delivery
	
	cd "$Originaldir\redelivery\linkage"
	
	import delimited "hes_procedures_epi_21_000362_delivery2_DM.txt", clear
	export delimited "$Rawdatadir\redelivery may 23\linkage\tabdelimited\hes_procedures_23.txt", replace 
	save "$Rawdatadir\redelivery may 23\linkage\stata\hes_procedures_23.dta", replace
	
********************************************************************************

* Save HES death in rawdata folder

	* September 2021 delivery

	cd "$Originaldir\linkage"
	
	import delimited "death_patient_21_000362_request2_redelivery.txt", clear
	export delimited "$Rawdatadir\original sept 21\linkage\tabdelimited\hes_death.txt", replace
	save "$Rawdatadir\original sept 21\linkage\stata\hes_death.dta", replace
	
	* May 2023 delivery
	
	cd "$Originaldir\redelivery\linkage"
	
	import delimited "death_patient_21_000362_delivery2_DM.txt", clear
	export delimited "$Rawdatadir\redelivery may 23\linkage\tabdelimited\hes_death_23.txt", replace 
	save "$Rawdatadir\redelivery may 23\linkage\stata\hes_death_23.dta", replace
	
********************************************************************************

* DEPRESSION *

********************************************************************************
	
* Save CPRD Therapy files in rawdata folder

	cd "$Originaldir\cohort 1\362_cohort1dep_Extract\Therapy" 
	
	forvalues x=1/6 {

		import delimited "362_cohort1dep_Extract_Therapy_00`x'.txt", clear
		export delimited "$Rawdatadir\original sept 21\cohort 1\tabdelimited\Therapy_dep_0`x'.txt", replace
		save "$Rawdatadir\original sept 21\cohort 1\stata\Therapy_dep_0`x'.dta", replace
	
	}
	
********************************************************************************
	
* Save CPRD Test files in rawdata folder
	
	cd "$Originaldir\cohort 1\362_cohort1dep_Extract\Test" 
	
	forvalues x=1/5 {

		import delimited "362_cohort1dep_Extract_Test_00`x'.txt", clear
		export delimited "$Rawdatadir\original sept 21\cohort 1\tabdelimited\Test_dep_0`x'.txt", replace
		save "$Rawdatadir\original sept 21\cohort 1\stata\Test_dep_0`x'.dta", replace
	
	}
	
********************************************************************************
	
* Save CPRD Staff files in rawdata folder
	
	cd "$Originaldir\cohort 1\362_cohort1dep_Extract\Staff" 

	import delimited "362_cohort1dep_Extract_Staff_001.txt", clear
	export delimited "$Rawdatadir\original sept 21\cohort 1\tabdelimited\Staff_dep_01.txt", replace
	save "$Rawdatadir\original sept 21\cohort 1\stata\Staff_dep_01.dta", replace
	
********************************************************************************
	
* Save CPRD Referral files in rawdata folder
	
	cd "$Originaldir\cohort 1\362_cohort1dep_Extract\Referral" 

	import delimited "362_cohort1dep_Extract_Referral_001.txt", clear
	export delimited "$Rawdatadir\original sept 21\cohort 1\tabdelimited\Referral_dep_01.txt", replace
	save "$Rawdatadir\original sept 21\cohort 1\stata\Referral_dep_01.dta", replace

********************************************************************************

* Save CPRD Practice files in rawdata folder
	
	cd "$Originaldir\cohort 1\362_cohort1dep_Extract\Practice" 

	import delimited "362_cohort1dep_Extract_Practice_001.txt", clear
	export delimited "$Rawdatadir\original sept 21\cohort 1\tabdelimited\Practice_dep_01.txt", replace
	save "$Rawdatadir\original sept 21\cohort 1\stata\Practice_dep_01.dta", replace
	
********************************************************************************
	
* Save CPRD Patient files in rawdata folder
	
	cd "$Originaldir\cohort 1\362_cohort1dep_Extract\Patient" 

	import delimited "362_cohort1dep_Extract_Patient_001.txt", clear
	export delimited "$Rawdatadir\original sept 21\cohort 1\tabdelimited\Patient_dep_01.txt", replace
	save "$Rawdatadir\original sept 21\cohort 1\stata\Patient_dep_01.dta", replace
	
********************************************************************************
	
* Save CPRD Immunisation files in rawdata folder
	
	cd "$Originaldir\cohort 1\362_cohort1dep_Extract\Immunisation" 

	import delimited "362_cohort1dep_Extract_Immunisation_001.txt", clear
	export delimited "$Rawdatadir\original sept 21\cohort 1\tabdelimited\Immunisation_dep_01.txt", replace
	save "$Rawdatadir\original sept 21\cohort 1\stata\Immunisation_dep_01.dta", replace

********************************************************************************
	
* Save CPRD Consultation files in rawdata folder
	
	cd "$Originaldir\cohort 1\362_cohort1dep_Extract\Consultation" 
	
	forvalues x=1/5 {

		import delimited "362_cohort1dep_Extract_Consultation_00`x'.txt", clear
		export delimited "$Rawdatadir\original sept 21\cohort 1\tabdelimited\Consultation_dep_0`x'.txt", replace
		save "$Rawdatadir\original sept 21\cohort 1\stata\Consultation_dep_0`x'.dta", replace
	
	}
	
********************************************************************************
	
* Save CPRD Clinical files in rawdata folder
	
	cd "$Originaldir\cohort 1\362_cohort1dep_Extract\Clinical" 
	
	forvalues x=1/6 {

		import delimited "362_cohort1dep_Extract_Clinical_00`x'.txt", clear
		export delimited "$Rawdatadir\original sept 21\cohort 1\tabdelimited\Clinical_dep_0`x'.txt", replace
		save "$Rawdatadir\original sept 21\cohort 1\stata\Clinical_dep_0`x'.dta", replace
	
	}

********************************************************************************
	
* Save CPRD Additional files in rawdata folder
	
	cd "$Originaldir\cohort 1\362_cohort1dep_Extract\Additional" 

	import delimited "362_cohort1dep_Extract_Additional_001.txt", clear
	export delimited "$Rawdatadir\original sept 21\cohort 1\tabdelimited\Additional_dep_01.txt", replace
	save "$Rawdatadir\original sept 21\cohort 1\stata\Additional_dep_01.dta", replace

********************************************************************************

* DIABETES *

********************************************************************************
	
* Save CPRD Therapy files in rawdata folder

	cd "$Originaldir\cohort 1\362_cohort1dia_Extract\Therapy" 
	
	forvalues x=1/2 {

		import delimited "362_cohort1dia_Extract_Therapy_00`x'.txt", clear
		export delimited "$Rawdatadir\original sept 21\cohort 1\tabdelimited\Therapy_dia_0`x'.txt", replace
		save "$Rawdatadir\original sept 21\cohort 1\stata\Therapy_dia_0`x'.dta", replace
	
	}
	
********************************************************************************
	
* Save CPRD Test files in rawdata folder
	
	cd "$Originaldir\cohort 1\362_cohort1dia_Extract\Test" 
	
	forvalues x=1/2 {

		import delimited "362_cohort1dia_Extract_Test_00`x'.txt", clear
		export delimited "$Rawdatadir\original sept 21\cohort 1\tabdelimited\Test_dia_0`x'.txt", replace
		save "$Rawdatadir\original sept 21\cohort 1\stata\Test_dia_0`x'.dta", replace
	
	}

********************************************************************************
	
* Save CPRD Staff files in rawdata folder
	
	cd "$Originaldir\cohort 1\362_cohort1dia_Extract\Staff" 

	import delimited "362_cohort1dia_Extract_Staff_001.txt", clear
	export delimited "$Rawdatadir\original sept 21\cohort 1\tabdelimited\Staff_dia_01.txt", replace
	save "$Rawdatadir\original sept 21\cohort 1\stata\Staff_dia_01.dta", replace
	
********************************************************************************
	
* Save CPRD Referral files in rawdata folder
	
	cd "$Originaldir\cohort 1\362_cohort1dia_Extract\Referral" 

	import delimited "362_cohort1dia_Extract_Referral_001.txt", clear
	export delimited "$Rawdatadir\original sept 21\cohort 1\tabdelimited\Referral_dia_01.txt", replace
	save "$Rawdatadir\original sept 21\cohort 1\stata\Referral_dia_01.dta", replace

********************************************************************************

* Save CPRD Practice files in rawdata folder
	
	cd "$Originaldir\cohort 1\362_cohort1dia_Extract\Practice" 

	import delimited "362_cohort1dia_Extract_Practice_001.txt", clear
	export delimited "$Rawdatadir\original sept 21\cohort 1\tabdelimited\Practice_dia_01.txt", replace
	save "$Rawdatadir\original sept 21\cohort 1\stata\Practice_dia_01.dta", replace
	
********************************************************************************
	
* Save CPRD Patient files in rawdata folder
	
	cd "$Originaldir\cohort 1\362_cohort1dia_Extract\Patient" 

	import delimited "362_cohort1dia_Extract_Patient_001.txt", clear
	export delimited "$Rawdatadir\original sept 21\cohort 1\tabdelimited\Patient_dia_01.txt", replace
	save "$Rawdatadir\original sept 21\cohort 1\stata\Patient_dia_01.dta", replace
	
********************************************************************************
	
* Save CPRD Immunisation files in rawdata folder
	
	cd "$Originaldir\cohort 1\362_cohort1dia_Extract\Immunisation" 

	import delimited "362_cohort1dia_Extract_Immunisation_001.txt", clear
	export delimited "$Rawdatadir\original sept 21\cohort 1\tabdelimited\Immunisation_dia_01.txt", replace
	save "$Rawdatadir\original sept 21\cohort 1\stata\Immunisation_dia_01.dta", replace

********************************************************************************
	
* Save CPRD Consultation files in rawdata folder
	
	cd "$Originaldir\cohort 1\362_cohort1dia_Extract\Consultation" 
	
	forvalues x=1/2 {

		import delimited "362_cohort1dia_Extract_Consultation_00`x'.txt", clear
		export delimited "$Rawdatadir\original sept 21\cohort 1\tabdelimited\Consultation_dia_0`x'.txt", replace
		save "$Rawdatadir\original sept 21\cohort 1\stata\Consultation_dia_0`x'.dta", replace
	
	}
	
********************************************************************************
	
* Save CPRD Clinical files in rawdata folder
	
	cd "$Originaldir\cohort 1\362_cohort1dia_Extract\Clinical" 
	
	forvalues x=1/2 {

		import delimited "362_cohort1dia_Extract_Clinical_00`x'.txt", clear
		export delimited "$Rawdatadir\original sept 21\cohort 1\tabdelimited\Clinical_dia_0`x'.txt", replace
		save "$Rawdatadir\original sept 21\cohort 1\stata\Clinical_dia_0`x'.dta", replace
	
	}

********************************************************************************
	
* Save CPRD Additional files in rawdata folder
	
	cd "$Originaldir\cohort 1\362_cohort1dia_Extract\Additional" 

	import delimited "362_cohort1dia_Extract_Additional_001.txt", clear
	export delimited "$Rawdatadir\original sept 21\cohort 1\tabdelimited\Additional_dia_01.txt", replace
	save "$Rawdatadir\original sept 21\cohort 1\stata\Additional_dia_01.dta", replace

********************************************************************************

* HYPERTENSION *

********************************************************************************
	
* Save CPRD Therapy files in rawdata folder

	cd "$Originaldir\cohort 1\362_cohort1hyt_Extract\Therapy" 
	
	forvalues x=1/3 {

		import delimited "362_cohort1hyt_Extract_Therapy_00`x'.txt", clear
		export delimited "$Rawdatadir\original sept 21\cohort 1\tabdelimited\Therapy_hyt_0`x'.txt", replace
		save "$Rawdatadir\original sept 21\cohort 1\stata\Therapy_hyt_0`x'.dta", replace
	
	}
	
********************************************************************************
	
* Save CPRD Test files in rawdata folder
	
	cd "$Originaldir\cohort 1\362_cohort1hyt_Extract\Test"
	
	forvalues x=1/2 {

		import delimited "362_cohort1hyt_Extract_Test_00`x'.txt", clear
		export delimited "$Rawdatadir\original sept 21\cohort 1\tabdelimited\Test_hyt_0`x'.txt", replace
		save "$Rawdatadir\original sept 21\cohort 1\stata\Test_hyt_0`x'.dta", replace
	
	}
	
********************************************************************************
	
* Save CPRD Staff files in rawdata folder
	
	cd "$Originaldir\cohort 1\362_cohort1hyt_Extract\Staff" 

	import delimited "362_cohort1hyt_Extract_Staff_001.txt", clear
	export delimited "$Rawdatadir\original sept 21\cohort 1\tabdelimited\Staff_hyt_01.txt", replace
	save "$Rawdatadir\original sept 21\cohort 1\stata\Staff_hyt_01.dta", replace
	
********************************************************************************
	
* Save CPRD Referral files in rawdata folder
	
	cd "$Originaldir\cohort 1\362_cohort1hyt_Extract\Referral" 

	import delimited "362_cohort1hyt_Extract_Referral_001.txt", clear
	export delimited "$Rawdatadir\original sept 21\cohort 1\tabdelimited\Referral_hyt_01.txt", replace
	save "$Rawdatadir\original sept 21\cohort 1\stata\Referral_hyt_01.dta", replace

********************************************************************************

* Save CPRD Practice files in rawdata folder
	
	cd "$Originaldir\cohort 1\362_cohort1hyt_Extract\Practice" 

	import delimited "362_cohort1hyt_Extract_Practice_001.txt", clear
	export delimited "$Rawdatadir\original sept 21\cohort 1\tabdelimited\Practice_hyt_01.txt", replace
	save "$Rawdatadir\original sept 21\cohort 1\stata\Practice_hyt_01.dta", replace
	
********************************************************************************
	
* Save CPRD Patient files in rawdata folder
	
	cd "$Originaldir\cohort 1\362_cohort1hyt_Extract\Patient" 

	import delimited "362_cohort1hyt_Extract_Patient_001.txt", clear
	export delimited "$Rawdatadir\original sept 21\cohort 1\tabdelimited\Patient_hyt_01.txt", replace
	save "$Rawdatadir\original sept 21\cohort 1\stata\Patient_hyt_01.dta", replace
	
********************************************************************************
	
* Save CPRD Immunisation files in rawdata folder
	
	cd "$Originaldir\cohort 1\362_cohort1hyt_Extract\Immunisation" 

	import delimited "362_cohort1hyt_Extract_Immunisation_001.txt", clear
	export delimited "$Rawdatadir\original sept 21\cohort 1\tabdelimited\Immunisation_hyt_01.txt", replace
	save "$Rawdatadir\original sept 21\cohort 1\stata\Immunisation_hyt_01.dta", replace

********************************************************************************
	
* Save CPRD Consultation files in rawdata folder
	
	cd "$Originaldir\cohort 1\362_cohort1hyt_Extract\Consultation" 
	
	forvalues x=1/2 {

		import delimited "362_cohort1hyt_Extract_Consultation_00`x'.txt", clear
		export delimited "$Rawdatadir\original sept 21\cohort 1\tabdelimited\Consultation_hyt_0`x'.txt", replace
		save "$Rawdatadir\original sept 21\cohort 1\stata\Consultation_hyt_0`x'.dta", replace
	
	}
	
********************************************************************************
	
* Save CPRD Clinical files in rawdata folder
	
	cd "$Originaldir\cohort 1\362_cohort1hyt_Extract\Clinical" 
	
	forvalues x=1/2 {

		import delimited "362_cohort1hyt_Extract_Clinical_00`x'.txt", clear
		export delimited "$Rawdatadir\original sept 21\cohort 1\tabdelimited\Clinical_hyt_0`x'.txt", replace
		save "$Rawdatadir\original sept 21\cohort 1\stata\Clinical_hyt_0`x'.dta", replace
	
	}

********************************************************************************
	
* Save CPRD Additional files in rawdata folder
	
	cd "$Originaldir\cohort 1\362_cohort1hyt_Extract\Additional" 

	import delimited "362_cohort1hyt_Extract_Additional_001.txt", clear
	export delimited "$Rawdatadir\original sept 21\cohort 1\tabdelimited\Additional_hyt_01.txt", replace
	save "$Rawdatadir\original sept 21\cohort 1\stata\Additional_hyt_01.dta", replace

********************************************************************************

* THYROID PROBLEMS *

********************************************************************************
	
* Save CPRD Therapy files in rawdata folder

	cd "$Originaldir\cohort 1\362_cohort1thy_Extract\Therapy" 
	
	forvalues x=1/2 {

		import delimited "362_cohort1thy_Extract_Therapy_00`x'.txt", clear
		export delimited "$Rawdatadir\original sept 21\cohort 1\tabdelimited\Therapy_thy_0`x'.txt", replace
		save "$Rawdatadir\original sept 21\cohort 1\stata\Therapy_thy_0`x'.dta", replace
	
	}
	
********************************************************************************
	
* Save CPRD Test files in rawdata folder
	
	cd "$Originaldir\cohort 1\362_cohort1thy_Extract\Test" 

	import delimited "362_cohort1thy_Extract_Test_001.txt", clear
	export delimited "$Rawdatadir\original sept 21\cohort 1\tabdelimited\Test_thy_01.txt", replace
	save "$Rawdatadir\original sept 21\cohort 1\stata\Test_thy_01.dta", replace
	
********************************************************************************
	
* Save CPRD Staff files in rawdata folder
	
	cd "$Originaldir\cohort 1\362_cohort1thy_Extract\Staff" 

	import delimited "362_cohort1thy_Extract_Staff_001.txt", clear
	export delimited "$Rawdatadir\original sept 21\cohort 1\tabdelimited\Staff_thy_01.txt", replace
	save "$Rawdatadir\original sept 21\cohort 1\stata\Staff_thy_01.dta", replace
	
********************************************************************************
	
* Save CPRD Referral files in rawdata folder
	
	cd "$Originaldir\cohort 1\362_cohort1thy_Extract\Referral" 

	import delimited "362_cohort1thy_Extract_Referral_001_20210921201509.txt", clear
	export delimited "$Rawdatadir\original sept 21\cohort 1\tabdelimited\Referral_thy_01.txt", replace
	save "$Rawdatadir\original sept 21\cohort 1\stata\Referral_thy_01.dta", replace

********************************************************************************

* Save CPRD Practice files in rawdata folder
	
	cd "$Originaldir\cohort 1\362_cohort1thy_Extract\Practice" 

	import delimited "362_cohort1thy_Extract_Practice_001.txt", clear
	export delimited "$Rawdatadir\original sept 21\cohort 1\tabdelimited\Practice_thy_01.txt", replace
	save "$Rawdatadir\original sept 21\cohort 1\stata\Practice_thy_01.dta", replace
	
********************************************************************************
	
* Save CPRD Patient files in rawdata folder
	
	cd "$Originaldir\cohort 1\362_cohort1thy_Extract\Patient" 

	import delimited "362_cohort1thy_Extract_Patient_001.txt", clear
	export delimited "$Rawdatadir\original sept 21\cohort 1\tabdelimited\Patient_thy_01.txt", replace
	save "$Rawdatadir\original sept 21\cohort 1\stata\Patient_thy_01.dta", replace
	
********************************************************************************
	
* Save CPRD Immunisation files in rawdata folder
	
	cd "$Originaldir\cohort 1\362_cohort1thy_Extract\Immunisation" 

	import delimited "362_cohort1thy_Extract_Immunisation_001_20210921201531.txt", clear
	export delimited "$Rawdatadir\original sept 21\cohort 1\tabdelimited\Immunisation_thy_01.txt", replace
	save "$Rawdatadir\original sept 21\cohort 1\stata\Immunisation_thy_01.dta", replace

********************************************************************************
	
* Save CPRD Consultation files in rawdata folder
	
	cd "$Originaldir\cohort 1\362_cohort1thy_Extract\Consultation" 

	import delimited "362_cohort1thy_Extract_Consultation_001.txt", clear
	export delimited "$Rawdatadir\original sept 21\cohort 1\tabdelimited\Consultation_thy_01.txt", replace
	save "$Rawdatadir\original sept 21\cohort 1\stata\Consultation_thy_01.dta", replace
	
********************************************************************************
	
* Save CPRD Clinical files in rawdata folder
	
	cd "$Originaldir\cohort 1\362_cohort1thy_Extract\Clinical" 

	import delimited "362_cohort1thy_Extract_Clinical_001.txt", clear
	export delimited "$Rawdatadir\original sept 21\cohort 1\tabdelimited\Clinical_thy_01.txt", replace
	save "$Rawdatadir\original sept 21\cohort 1\stata\Clinical_thy_01.dta", replace

********************************************************************************
	
* Save CPRD Additional files in rawdata folder
	
	cd "$Originaldir\cohort 1\362_cohort1thy_Extract\Additional" 

	import delimited "362_cohort1thy_Extract_Additional_001.txt", clear
	export delimited "$Rawdatadir\original sept 21\cohort 1\tabdelimited\Additional_thy_01.txt", replace
	save "$Rawdatadir\original sept 21\cohort 1\stata\Additional_thy_01.dta", replace

********************************************************************************

* MAY RE-DELIVERY 2023

* ADDITIONAL

	forvalues x=0/10 {
		forvalues y=1/2 {
		
		import delimited "$Originaldir\redelivery\primary care\21_000362_patientlist`x'_Extract\21_000362_patientlist`x'_Extract\Additional\21_000362_patientlist`x'_Extract_Additional_00`y'.txt", clear
		save "$Rawdatadir\redelivery may 23\primary care\Additional_0`y'_`x'.dta", replace
	
		}
	}
	
* CLINICAL 

	foreach x in 0 2 4 7 {
		forvalues y=1/8 {
		
		import delimited "$Originaldir\redelivery\primary care\21_000362_patientlist`x'_Extract\21_000362_patientlist`x'_Extract\Clinical\21_000362_patientlist`x'_Extract_Clinical_00`y'.txt", clear
		save "$Rawdatadir\redelivery may 23\primary care\Clinical_0`y'_`x'.dta", replace
	
		}
	}
	
	foreach x in 1 3 5 6 10 {
		forvalues y=1/9 {
		
		import delimited "$Originaldir\redelivery\primary care\21_000362_patientlist`x'_Extract\21_000362_patientlist`x'_Extract\Clinical\21_000362_patientlist`x'_Extract_Clinical_00`y'.txt", clear
		save "$Rawdatadir\redelivery may 23\primary care\Clinical_0`y'_`x'.dta", replace
	
		}
	}
	
	foreach x in 8 9 {
		foreach y in 01 02 03 04 05 06 07 08 09 10 {
		
		import delimited "$Originaldir\redelivery\primary care\21_000362_patientlist`x'_Extract\21_000362_patientlist`x'_Extract\Clinical\21_000362_patientlist`x'_Extract_Clinical_0`y'.txt", clear
		save "$Rawdatadir\redelivery may 23\primary care\Clinical_`y'_`x'.dta", replace
	
		}
	}
	
* CONSULTATION

	foreach x in 0 2 4 5 7 {
		forvalues y=1/8 {
		
		import delimited "$Originaldir\redelivery\primary care\21_000362_patientlist`x'_Extract\21_000362_patientlist`x'_Extract\Consultation\21_000362_patientlist`x'_Extract_Consultation_00`y'.txt", clear
		save "$Rawdatadir\redelivery may 23\primary care\Consultation_0`y'_`x'.dta", replace
	
		}
	}
	
	foreach x in 1 3 6 {
		forvalues y=1/9 {
		
		import delimited "$Originaldir\redelivery\primary care\21_000362_patientlist`x'_Extract\21_000362_patientlist`x'_Extract\Consultation\21_000362_patientlist`x'_Extract_Consultation_00`y'.txt", clear
		save "$Rawdatadir\redelivery may 23\primary care\Consultation_0`y'_`x'.dta", replace
	
		}
	}
	
	foreach x in 8 9 10 {
		foreach y in 01 02 03 04 05 06 07 08 09 10 {
		
		import delimited "$Originaldir\redelivery\primary care\21_000362_patientlist`x'_Extract\21_000362_patientlist`x'_Extract\Consultation\21_000362_patientlist`x'_Extract_Consultation_0`y'.txt", clear
		save "$Rawdatadir\redelivery may 23\primary care\Consultation_`y'_`x'.dta", replace
	
		}
	}
	
* IMMUNISATION

	forvalues x=0/10 {
		
		import delimited "$Originaldir\redelivery\primary care\21_000362_patientlist`x'_Extract\21_000362_patientlist`x'_Extract\Immunisation\21_000362_patientlist`x'_Extract_Immunisation_001.txt", clear
		save "$Rawdatadir\redelivery may 23\primary care\Immunisation_01_`x'.dta", replace
	
	}

* PATIENT

	forvalues x=0/10 {	
		
		import delimited "$Originaldir\redelivery\primary care\21_000362_patientlist`x'_Extract\21_000362_patientlist`x'_Extract\Patient\21_000362_patientlist`x'_Extract_Patient_001.txt", clear
		save "$Rawdatadir\redelivery may 23\primary care\Patient_01_`x'.dta", replace
	
	}
	
* PRACTICE

	forvalues x=0/10 {	
		
		import delimited "$Originaldir\redelivery\primary care\21_000362_patientlist`x'_Extract\21_000362_patientlist`x'_Extract\Practice\21_000362_patientlist`x'_Extract_Practice_001.txt", clear
		save "$Rawdatadir\redelivery may 23\primary care\Practice_01_`x'.dta", replace
	
	}
	
* REFERRAL 

	forvalues x=0/10 {	
		
		import delimited "$Originaldir\redelivery\primary care\21_000362_patientlist`x'_Extract\21_000362_patientlist`x'_Extract\Referral\21_000362_patientlist`x'_Extract_Referral_001.txt", clear
		save "$Rawdatadir\redelivery may 23\primary care\Referral_01_`x'.dta", replace
	
	}
	
* STAFF

	forvalues x=0/10 {	
		
		import delimited "$Originaldir\redelivery\primary care\21_000362_patientlist`x'_Extract\21_000362_patientlist`x'_Extract\Staff\21_000362_patientlist`x'_Extract_Staff_001.txt", clear
		save "$Rawdatadir\redelivery may 23\primary care\Staff_01_`x'.dta", replace
	
	}
	
* TEST

	foreach x in 4 {
		forvalues y=1/6 {
		
		import delimited "$Originaldir\redelivery\primary care\21_000362_patientlist`x'_Extract\21_000362_patientlist`x'_Extract\Test\21_000362_patientlist`x'_Extract_Test_00`y'.txt", clear
		save "$Rawdatadir\redelivery may 23\primary care\Test_0`y'_`x'.dta", replace
	
		}
	}
	
	foreach x in 0 1 2 5 6 7 {
		forvalues y=1/7 {
		
		import delimited "$Originaldir\redelivery\primary care\21_000362_patientlist`x'_Extract\21_000362_patientlist`x'_Extract\Test\21_000362_patientlist`x'_Extract_Test_00`y'.txt", clear
		save "$Rawdatadir\redelivery may 23\primary care\Test_0`y'_`x'.dta", replace
	
		}
	}
	
	foreach x in 3 {
		forvalues y=1/8 {
		
		import delimited "$Originaldir\redelivery\primary care\21_000362_patientlist`x'_Extract\21_000362_patientlist`x'_Extract\Test\21_000362_patientlist`x'_Extract_Test_00`y'.txt", clear
		save "$Rawdatadir\redelivery may 23\primary care\Test_0`y'_`x'.dta", replace
	
		}
	}
	
	foreach x in 8 9 10 {
		forvalues y=1/9 {
		
		import delimited "$Originaldir\redelivery\primary care\21_000362_patientlist`x'_Extract\21_000362_patientlist`x'_Extract\Test\21_000362_patientlist`x'_Extract_Test_00`y'.txt", clear
		save "$Rawdatadir\redelivery may 23\primary care\Test_0`y'_`x'.dta", replace
	
		}
	}
	
* THERAPY

	foreach x in 0 {
		foreach y in 01 02 03 04 05 06 07 08 09 10 11 12 13 {
		
		import delimited "$Originaldir\redelivery\primary care\21_000362_patientlist`x'_Extract\21_000362_patientlist`x'_Extract\Therapy\21_000362_patientlist`x'_Extract_Therapy_0`y'.txt", clear
		save "$Rawdatadir\redelivery may 23\primary care\Therapy_`y'_`x'.dta", replace
	
		}
	}
	
	foreach x in 1 2 3 4 5 7 {
		foreach y in 01 02 03 04 05 06 07 08 09 10 11 12 13 14 {
		
		import delimited "$Originaldir\redelivery\primary care\21_000362_patientlist`x'_Extract\21_000362_patientlist`x'_Extract\Therapy\21_000362_patientlist`x'_Extract_Therapy_0`y'.txt", clear
		save "$Rawdatadir\redelivery may 23\primary care\Therapy_`y'_`x'.dta", replace
	
		}
	}
	
	foreach x in 6 {
		foreach y in 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 {
		
		import delimited "$Originaldir\redelivery\primary care\21_000362_patientlist`x'_Extract\21_000362_patientlist`x'_Extract\Therapy\21_000362_patientlist`x'_Extract_Therapy_0`y'.txt", clear
		save "$Rawdatadir\redelivery may 23\primary care\Therapy_`y'_`x'.dta", replace
	
		}
	}
	
	foreach x in 8 {
		foreach y in 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 {
		
		import delimited "$Originaldir\redelivery\primary care\21_000362_patientlist`x'_Extract\21_000362_patientlist`x'_Extract\Therapy\21_000362_patientlist`x'_Extract_Therapy_0`y'.txt", clear
		save "$Rawdatadir\redelivery may 23\primary care\Therapy_`y'_`x'.dta", replace
	
		}
	}
	
	foreach x in 10 {
		foreach y in 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 {
		
		import delimited "$Originaldir\redelivery\primary care\21_000362_patientlist`x'_Extract\21_000362_patientlist`x'_Extract\Therapy\21_000362_patientlist`x'_Extract_Therapy_0`y'.txt", clear
		save "$Rawdatadir\redelivery may 23\primary care\Therapy_`y'_`x'.dta", replace
	
		}
	}

	
	foreach x in 9 {
		foreach y in 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 {
		
		import delimited "$Originaldir\redelivery\primary care\21_000362_patientlist`x'_Extract\21_000362_patientlist`x'_Extract\Therapy\21_000362_patientlist`x'_Extract_Therapy_0`y'.txt", clear
		save "$Rawdatadir\redelivery may 23\primary care\Therapy_`y'_`x'.dta", replace
	
		}
	}
	
********************************************************************************

* Stop logging 

	log close
	
********************************************************************************
