********************************************************************************

* Investigating the builds from the two data deliveries from UoB (delivery 1) and CPRD (delivery 2)

* Author: Flo Martin

* Date: 06/06/2023

********************************************************************************

* Datasets generated by this do-file

	* Builds dataset for formatting the CPRD datasets

********************************************************************************

* Start logging
	
	log using "$Logdir\1_formatting\1a_builds.txt", replace
	
********************************************************************************

use "$Originaldir\all_patient.dta", clear
	
	drop if accept==0
	
	count // 20,340,046 acceptable patients in the June 21 build
	
	merge 1:1 patid using "$Originaldir\acceptable_pats_from_utspracts_2021_09.dta", force
	
	count if _m==3 // 20,324,392 accetable patients in Sept 21 build
	
	count if _m==2 // 154,252 new patients between Jun and Sept
	
	count if _m==1 // 15,654 patients who have withdrawn consent
	
	rename _m different_builds
	label define builds_lb 1"Withdrawn consent" 2"New patients" 3"In June and Sept"
	label values different_builds builds_lb
	
	keep patid different_builds
	
	save "$Tempdatadir\builds.dta", replace
	
	/* By requesting June 21, we would get back the 15,654 patients who withdrew consent and would retain those of the Sept 21 (154,252 patients) who have an indication but would not get back those who don't by requesting the June 21 build */
	
	use "$Tempdatadir\builds.dta", clear
	
	keep if different_builds==2
	count
	
	keep patid 
	
	merge 1:1 patid using "$Datadir\formatted_cprd_data\All_Patient.dta", keepusing(patid)
	
	count if _m==3 // 1 patient is retained in our indication-based samples
	
	keep if _m==3
	count // the mum patient who is in the Sept data but not the June TO EXCLUDE
	
	drop _m
	
	save "$Tempdatadir\sept patient to exclude.dta", replace
	
	use "$Tempdatadir\builds.dta", clear
	
	keep if different_builds==2
	
	count
	
	merge 1:1 patid using "$Cohorttwodir\All_Patient.dta", keepusing(patid)
	
	* none of the babies are in Sept and not June (presumably because the MBL is from June or before?)
	
	count if _m==2 // the remaining 154,251 patients are dropped on the basis of not having a indication of interest in the timeframe of interest 
	
	/* Conclusion - getting the remainder of the primary care cut is unlikely to be problematic in terms of who of the new patients are retained because they're mostly dropped - it will just require an note in the appendix highlighting that we have gained patients/practices who withdrew consent between Jun - Sept */
	
	keep if _m==1
	count // new patients NOT in our existing sample (154,251)
	
	drop _m
	
	merge 1:m patid using "[path]\9_additional_data_request_2022\Preg Reg and MBL\pregnancyregister_redelivered.dta"
	
	codebook patid if _m==3 // of the new patients we'd be losing by getting the June 21 build this represents 59,005 pregnancies among 23,676 patients
	
	disp (59005/7834113)*100 // 0.75% of the Pregnancy Register pregnancies
	
	save "$Tempdatadir\new patients.dta", replace
	
	
	import delimited "[path]\9_additional_data_request_2022\flo_patids.txt", clear
	
	count
	
	merge 1:m patid using "[path]\9_additional_data_request_2022\Preg Reg and MBL\pregnancyregister_redelivered.dta"
	
	count if _m==2 | _m==3
	
	merge 1:1 patid pregid using "[path]\9_additional_data_request_2022\Preg Reg and MBL\pregnancyregister_redelivered.dta", clear
	
	count // 7,703,538 pregnancies in the Sept 21 pregnancy register

	// we currently have 1,316,672 pregnancies 
	
	rename _m original
	
	merge 1:1 patid pregid using "[path]\Final\pregnancy_register_21_000362_delivery2_DM.dta"
	
	tab original if _m==1
	
	keep if _m==1
	
	keep patid
	
	
	use "$Originaldir\pregnancyregister.dta", clear
	
	count
	
	merge 1:1 patid pregid using "[path]\Final\pregnancy_register_21_000362_delivery2_DM.dta"
	
	count
	
	merge m:1 patid using "[path]\9_additional_data_request_2022\Denominators\Denominator_files\2021_06\all_patient.dta", keep(3) nogen
	
	merge 1:1 patid pregid using "[path]\9_additional_data_request_2022\Preg Reg and MBL\pregnancyregister_redelivered.dta"
	
	duplicates drop // no duplicates
	
	
	use "$Datadir\formatted_cprd_data\All_Patient.dta", clear
	
	duplicates drop
	
	count // 428,163
	
	append using "[path]\9_additional_data_request_2022\flo_mum_patids.dta"
	
	duplicates drop
	
	count // 3,163,082
	
	merge 1:m patid using "[path]\Final\pregnancy_register_21_000362_delivery2_DM.dta"
	
	// 6,227,341 in new pregnancy register
	// 423,461 not matched
	
	keep if _m==1
	drop _m
	codebook patid
	
	merge 1:m patid using "$Datadir\formatted_linked_data\pregnancyregister.dta"
	
	tab accept _m
	
	rename _m unmatched
	
	tab unmatched
	
	merge m:1 patid using "[path]\9_additional_data_request_2022\Denominators\Denominator_files\2021_06\all_patient.dta", force

	drop if accept==0
	
	count // 20,340,046 acceptable patients in the June 21 build
	
	merge 1:1 patid using "[path]\denominators_2021_09_cprd_gold\acceptable_pats_from_utspracts_2021_09.dta", force
	
	duplicates drop patid pregid, force
	
	count
	
* Flow diagram

	use "[path]\9_additional_data_request_2022\Denominators\Denominator_files\2021_06\all_patient.dta", clear
	
	drop if accept==0
	
	merge 1:m patid using "$Tempdatadir\merged preg regs.dta", nogen keep(3)
	
	keep patid
	duplicates drop
	
	count

	merge 1:1 patid using "$Datadir\formatted_cprd_data\All_Patient"
	
	rename _m pregreg_vs_patient_sept
	
	merge 1:1 patid using "$Tempdatadir\builds.dta", nogen keep(3)
	
	merge 1:1 patid using "[path]\9_additional_data_request_2022\flo_mum_patids.dta"
	
	drop _m
	count
	
	merge 1:m patid using "$Tempdatadir\merged preg regs.dta", nogen keep(3)
	
	codebook patid

********************************************************************************

    * Stop logging

    log close

********************************************************************************
