********************************************************************************

* Label variables in each file type (Therapy, Test etc.) in data redelivery rawdata and generate & combine individual files to one master file

* Author: Flo Martin (adapted from scripts by Hein Heuvelman)

* Date: 07\06\2023

********************************************************************************

* Datasets generated by this do-file

	* Formatted CPRD data files (appended as All_*) stored in $Datadir

********************************************************************************

* Start logging
	
	log using "$Logdir\1_formatting\2_formatting original cprd.txt", replace
	
********************************************************************************

* Pregnancy Register

	use "$Rawdatadir\redelivery may 23\linkage\stata\pregnancyregister_23.dta", clear
	merge 1:1 patid pregid using "$Rawdatadir\redelivery feb 24\stata\pregnancyregister_24.dta", nogen

* Create numerical variables for eventdate and sysdate
		
	gen pregstart_num = date(pregstart, "DMY")
	format pregstart_num %td
			
	gen firstantenatal_num = date(firstantenatal, "DMY")
	format firstantenatal_num %td
				
	gen secondtrim_num = date(secondtrim, "DMY")
	format secondtrim_num %td				

	gen thirdtrim_num = date(thirdtrim, "DMY")
	format thirdtrim_num %td		
		
	gen pregend_num = date(pregend, "DMY")
	format pregend_num %td
			
* Label variables
		
	label variable patid "Patient ID"
	label variable pregid "Pregnancy ID"
	label variable mblbabies "Number of babies pregnancy is linked to in MBL"
	label variable babypatid "Patient ID for linked baby"
	label variable babymob "Baby's month of birth"
	label variable babyyob "Baby's year of birth"
	label variable totalpregs "Total number of identified pregnancy episodes"
	label variable pregnumber "Pregnancy episode number"
	label variable pregstart "Estimated start date of pregnancy - string"
	label variable firstantenatal "Date of earliest antenatal record within pregnancy - string"
	label variable startsource "Data source used to estimate pregnancy start date (see documentation)"
	label variable startadj "Flag to indicate whether pregnancy start date was adjusted (see documentation)"
	label variable secondtrim "Estimated start date of second trimester - string"
	label variable thirdtrim "Estimated start date of third trimester - string"
	label variable pregend "Estimated end date of pregnancy (see documentation) - string"
	label variable endsource "Data source used to estimate pregnancy end date (see documentation) - LB & SB only"
	label variable endadj "Flag to indicate whether pregnancy end date was adjusted (see documentation) - missing for pregnancies based on late pregnancy records"
	label variable gestdays "Estimated duration of pregnancy in gestational days"
	label variable matage "Mother's age at end of pregnancy in years"
	label variable outcome "Outcome of pregnancy (see documentation)"
	label variable preterm_ev "Flag to indicate evidence of preterm delivery (see documentation)"
	label variable postterm_ev "Flag to indicate evidence of a postterm delivery (see documentation)"
	label variable multiple_ev "Flag to indicate evidence of a multiple pregnancy (see documentation)"
	label variable conflict "Flag to indicate whether the pregnancy episode overlaps with another episode"
	label variable pregstart_num "Estimated start date of pregnancy - numerical"
	label variable firstantenatal_num "Date of earliest antenatal record within pregnancy - numerical"
	label variable secondtrim_num "Estimated start date of second trimester - numerical"
	label variable thirdtrim_num "Estimated start date of third trimester - numerical"
	label variable pregend_num "Estimated end date of pregnancy (see documentation) - numerical"
	
* Add category labels
	
	label define startsource_lb 1"Imputed" 2"EDD" 3"LMP" 4"GA at birth" 5"GA from antenatal record" 6"EDC" 7"HES delivery date minus gestat" 8"Imputed from HES delivery date" 9"Imputed from HES loss date"
	label values startsource startsource_lb
	
	label define startadj_lb 0"Not adjusted" 1"Due to antenatal records in the preceding 4 weeks" 2"Due to specific conflicts between the estimated pregnancy duration & records indicating GA at birth" 3"Both"
	label values startadj startadj_lb
	
	label define endsource_lb 1"Delivery record" 2"Postnatal record in mum's record" 3"Discharge date related to delivery" 4"Baby's DOB as recorded in the baby's medical record" 5"Postnatal record in the baby's medical record" 6"First postnatal consult in the baby's medical record" 7"HES delivery date" 8"HES loss date"
	label values endsource endsource_lb
	
	label define endadj_lb 0"Not adjusted" 1"Due to specific conflicts between the estimated pregnancy duration & records indicating GA at birth" 2"Due to prior adjustments to start date" 3"Both"
	label values endadj endadj_lb 
			
* Sort on patient ID and pregnancy ID
			
	sort patid pregid
				
* Compress data
		
	compress *
	
	append using "$Cohortonedir\formatted_linked_data\pregnancyregister.dta"
	
	duplicates drop
	
	duplicates tag patid pregid, gen(dup)
	tab dup
	drop dup
	
	count
			
	save "$Datadir\formatted_linked_data\pregnancyregister.dta", replace
	
********************************************************************************

* MOTHER BABY LINK

	use "$Rawdatadir\original sept 21\linkage\stata\mbl_baby.dta", clear
	append using "$Rawdatadir\redelivery may 23\linkage\stata\mbl_baby_23.dta"
	sort mumpatid babypatid
	drop mumbirthyear babybirthyear gender
	duplicates drop
	count //  1,588,465
	save "$Datadir\formatted_linked_data\mbl_baby.dta", replace
	
	use "$Rawdatadir\original sept 21\linkage\stata\mbl_mum.dta", clear
	append using "$Rawdatadir\redelivery may 23\linkage\stata\mbl_mum_23.dta"
	sort mumpatid babypatid
	drop mumbirthyear babybirthyear gender
	duplicates drop
	count // 1,588,451
	save "$Datadir\formatted_linked_data\mbl_mum.dta", replace

	use "$Datadir\formatted_linked_data\mbl_baby.dta", clear
	merge 1:1 babypatid using "$Datadir\formatted_linked_data\mbl_mum.dta"
	* 15 babies without mums? 1 mum without babies? 
	
	keep if _m==3
	drop _m
	save "$Datadir\formatted_linked_data\mbl.dta", replace
	
********************************************************************************

* THERAPY

* Generate numerical date variables, add variable labels, sort data on patid and eventdate and compress

	foreach number in 01 02 03 04 05 06 {
	
			use "$Rawdatadir\original sept 21\cohort 1\stata\Therapy_dep_`number'.dta", clear

		* Create numerical variables for eventdate and sysdate
		
			gen eventdate_num = date(eventdate, "DMY")
			format eventdate_num %td
			
			gen sysdate_num = date(sysdate, "DMY")
			format sysdate_num %td
		
		* Label variables
			
			label variable patid "Patient ID"
			label variable eventdate "Date of therapy event - string"
			label variable eventdate_num "Date of therapy event - numerical"
			label variable sysdate "Date entered on Vision - string"
			label variable sysdate_num "Date entered on Vision - numerical"
			label variable consid "Consultation ID: linkage with consultation file when used with pracid"
			label variable prodcode "CPRD code for treatment, selected by GP"
			label variable drugdmd "The mapped drug DMD code"
			label variable staffid "ID of staff entering data onto Vision, zero ==unknown"
			label variable dosageid "dosage ID: linkage with dosage info when used with pracid and eventtype therapy"
			label variable bnfcode "Chapter and section of British National Formulary pharmaceutical reference book"
			label variable qty "Total quantity entered by GP for prescribed product"
			label variable numdays "Number of treatment days prescribed for therapy event"
			label variable numpacks "Number of product packs prescribed for therapy event"
			label variable packtype "Pack size or type of prescribed product"
			label variable issueseq "Prescription part of repeat schedule"
			label variable prn "Indicates if the prescription is to be supplied 'as required'"
				
		* Sort on patient ID and eventdate
			
			sort patid eventdate_num
				
		* Compress data
		
			compress *
			
			save "$Rawdatadir\original sept 21\cohort 1\stata\Therapy_dep_`number'.dta", replace
		
	}

* Join all six Therapy files together to create one Therapy file in tempdata
	
	use "$Rawdatadir\original sept 21\cohort 1\stata\Therapy_dep_01.dta", clear
	append using "$Rawdatadir\original sept 21\cohort 1\stata\Therapy_dep_02.dta"
	append using "$Rawdatadir\original sept 21\cohort 1\stata\Therapy_dep_03.dta"
	append using "$Rawdatadir\original sept 21\cohort 1\stata\Therapy_dep_04.dta"
	append using "$Rawdatadir\original sept 21\cohort 1\stata\Therapy_dep_05.dta"
	append using "$Rawdatadir\original sept 21\cohort 1\stata\Therapy_dep_06.dta"
	
	duplicates report
	duplicates tag, gen(tag)
	tab tag
	duplicates drop	
	count
	drop tag
	
	save "$Tempdatadir\All_dep_Therapy.dta", replace
	
	foreach disease in dia thy {
		foreach number in 01 02 {
	
			use "$Rawdatadir\original sept 21\cohort 1\stata\Therapy_`disease'_`number'.dta", clear

		* Create numerical variables for eventdate and sysdate
		
			gen eventdate_num = date(eventdate, "DMY")
			format eventdate_num %td
			
			gen sysdate_num = date(sysdate, "DMY")
			format sysdate_num %td
		
		* Label variables
			
			label variable patid "Patient ID"
			label variable eventdate "Date of therapy event - string"
			label variable eventdate_num "Date of therapy event - numerical"
			label variable sysdate "Date entered on Vision - string"
			label variable sysdate_num "Date entered on Vision - numerical"
			label variable consid "Consultation ID: linkage with consultation file when used with pracid"
			label variable prodcode "CPRD code for treatment, selected by GP"
			label variable drugdmd "The mapped drug DMD code"
			label variable staffid "ID of staff entering data onto Vision, zero ==unknown"
			label variable dosageid "dosage ID: linkage with dosage info when used with pracid and eventtype therapy"
			label variable bnfcode "Chapter and section of British National Formulary pharmaceutical reference book"
			label variable qty "Total quantity entered by GP for prescribed product"
			label variable numdays "Number of treatment days prescribed for therapy event"
			label variable numpacks "Number of product packs prescribed for therapy event"
			label variable packtype "Pack size or type of prescribed product"
			label variable issueseq "Prescription part of repeat schedule"
			label variable prn "Indicates if the prescription is to be supplied 'as required'"
				
		* Sort on patient ID and eventdate
			
			sort patid eventdate_num
				
		* Compress data
		
			compress *
			
			save "$Rawdatadir\original sept 21\cohort 1\stata\Therapy_`disease'_`number'.dta", replace
		
		}	
	
	use "$Rawdatadir\original sept 21\cohort 1\stata\Therapy_`disease'_01.dta", clear
	append using "$Rawdatadir\original sept 21\cohort 1\stata\Therapy_`disease'_02.dta"

	duplicates report
	duplicates tag, gen(tag)
	tab tag
	duplicates drop	
	count
	drop tag
	
	save "$Tempdatadir\All_`disease'_Therapy.dta", replace
	
	}
	
	foreach number in 01 02 03 {
	
			use "$Rawdatadir\original sept 21\cohort 1\stata\Therapy_hyt_`number'.dta", clear

		* Create numerical variables for eventdate and sysdate
		
			gen eventdate_num = date(eventdate, "DMY")
			format eventdate_num %td
			
			gen sysdate_num = date(sysdate, "DMY")
			format sysdate_num %td
		
		* Label variables
			
			label variable patid "Patient ID"
			label variable eventdate "Date of therapy event - string"
			label variable eventdate_num "Date of therapy event - numerical"
			label variable sysdate "Date entered on Vision - string"
			label variable sysdate_num "Date entered on Vision - numerical"
			label variable consid "Consultation ID: linkage with consultation file when used with pracid"
			label variable prodcode "CPRD code for treatment, selected by GP"
			label variable drugdmd "The mapped drug DMD code"
			label variable staffid "ID of staff entering data onto Vision, zero ==unknown"
			label variable dosageid "dosage ID: linkage with dosage info when used with pracid and eventtype therapy"
			label variable bnfcode "Chapter and section of British National Formulary pharmaceutical reference book"
			label variable qty "Total quantity entered by GP for prescribed product"
			label variable numdays "Number of treatment days prescribed for therapy event"
			label variable numpacks "Number of product packs prescribed for therapy event"
			label variable packtype "Pack size or type of prescribed product"
			label variable issueseq "Prescription part of repeat schedule"
			label variable prn "Indicates if the prescription is to be supplied 'as required'"
				
		* Sort on patient ID and eventdate
			
			sort patid eventdate_num
				
		* Compress data
		
			compress *
			
			save "$Rawdatadir\original sept 21\cohort 1\stata\Therapy_hyt_`number'.dta", replace
		
	}

* Join all three Therapy files together to create one Therapy file in tempdata
	
	use "$Rawdatadir\original sept 21\cohort 1\stata\Therapy_hyt_01.dta", clear
	append using "$Rawdatadir\original sept 21\cohort 1\stata\Therapy_hyt_02.dta"
	append using "$Rawdatadir\original sept 21\cohort 1\stata\Therapy_hyt_03.dta"
	
	duplicates report
	duplicates tag, gen(tag)
	tab tag
	duplicates drop	
	count
	drop tag
	
	save "$Tempdatadir\All_hyt_Therapy.dta", replace
	
* Now append all the Therapy files from each disease area
	
	use "$Tempdatadir\All_dep_Therapy.dta", clear
	append using "$Tempdatadir\All_dia_Therapy.dta"
	append using "$Tempdatadir\All_hyt_Therapy.dta"
	append using "$Tempdatadir\All_thy_Therapy.dta"
	
	duplicates report
	duplicates tag, gen(tag)
	tab tag
	duplicates drop	
	count
	drop tag
	
	save "$Datadir\formatted_cprd_data\All_Therapy.dta", replace
	
********************************************************************************
	
* TEST

* Generate numerical date variables, add variable labels, sort data on patid and eventdate and compress

* Depression

	foreach number in 01 02 03 04 05 {
	
			use "$Rawdatadir\original sept 21\cohort 1\stata\Test_dep_`number'.dta", clear

		* Create numerical variables for eventdate and sysdate
		
			gen eventdate_num = date(eventdate, "DMY")
			format eventdate_num %td
			
			gen sysdate_num = date(sysdate, "DMY")
			format sysdate_num %td
		
		* Label variables
			
			label variable patid "Patient ID"
			label variable eventdate "Date of therapy event - string"
			label variable eventdate_num "Date of therapy event - numerical"
			label variable sysdate "Date entered on Vision - string"
			label variable sysdate_num "Date entered on Vision - numerical"
			label variable consid "Consultation ID: linkage with consultation file when used with pracid"
			label variable constype "Consultation type: category of event"
			label variable medcode "CPRD code for medical term, selected by GP"
			label variable sctid "The mapped SNOMED CT concept ID"
			label variable sctdescid "SNOMED description ID"
			label variable sctexpression "SNOMED expression"
			label variable sctmaptype "SNOMED mapping type"
			label variable sctmapversion "SNOMED mapping version"
			label variable sctisindicative "SCT is indicative"
			label variable sctisassured "SCT is assured"
			label variable staffid "ID of staff entering data onto Vision, zero ==unknown"
			label variable enttype "Entity type: structure data area in Vision where data was entered"
			label variable data1 "Depends on enttype: see CPRD data dictionary for further info"
			label variable data2 "Depends on enttype: see CPRD data dictionary for further info"
			label variable data3 "Depends on enttype: see CPRD data dictionary for further info"
			label variable data4 "Depends on enttype: see CPRD data dictionary for further info"
			label variable data5 "Depends on enttype: see CPRD data dictionary for further info"
			label variable data6 "Depends on enttype: see CPRD data dictionary for further info"
			label variable data7 "Depends on enttype: see CPRD data dictionary for further info"
			label variable data8 "Depends on enttype: see CPRD data dictionary for further info"
				
		* Sort on patient ID and eventdate
			
			sort patid eventdate_num
			
		* Compress data
		
			compress *
			
			save "$Rawdatadir\original sept 21\cohort 1\stata\Test_dep_`number'.dta", replace
		
	}
	
	use "$Rawdatadir\original sept 21\cohort 1\stata\Test_dep_01.dta", clear
	append using "$Rawdatadir\original sept 21\cohort 1\stata\Test_dep_02.dta"
	append using "$Rawdatadir\original sept 21\cohort 1\stata\Test_dep_03.dta"
	append using "$Rawdatadir\original sept 21\cohort 1\stata\Test_dep_04.dta"
	append using "$Rawdatadir\original sept 21\cohort 1\stata\Test_dep_05.dta"
	
	duplicates report
	duplicates tag, gen(tag)
	tab tag
	duplicates drop	
	count
	drop tag
	
	save "$Tempdatadir\All_dep_Test.dta", replace
	
* Diabetes and hypertension
	
	foreach disease in dia hyt {
		foreach number in 01 02 {
	
			use "$Rawdatadir\original sept 21\cohort 1\stata\Test_`disease'_`number'.dta", clear

		* Create numerical variables for eventdate and sysdate
		
			gen eventdate_num = date(eventdate, "DMY")
			format eventdate_num %td
			
			gen sysdate_num = date(sysdate, "DMY")
			format sysdate_num %td
		
		* Label variables
			
			label variable patid "Patient ID"
			label variable eventdate "Date of therapy event - string"
			label variable eventdate_num "Date of therapy event - numerical"
			label variable sysdate "Date entered on Vision - string"
			label variable sysdate_num "Date entered on Vision - numerical"
			label variable consid "Consultation ID: linkage with consultation file when used with pracid"
			label variable constype "Consultation type: category of event"
			label variable medcode "CPRD code for medical term, selected by GP"
			label variable sctid "The mapped SNOMED CT concept ID"
			label variable sctdescid "SNOMED description ID"
			label variable sctexpression "SNOMED expression"
			label variable sctmaptype "SNOMED mapping type"
			label variable sctmapversion "SNOMED mapping version"
			label variable sctisindicative "SCT is indicative"
			label variable sctisassured "SCT is assured"
			label variable staffid "ID of staff entering data onto Vision, zero ==unknown"
			label variable enttype "Entity type: structure data area in Vision where data was entered"
			label variable data1 "Depends on enttype: see CPRD data dictionary for further info"
			label variable data2 "Depends on enttype: see CPRD data dictionary for further info"
			label variable data3 "Depends on enttype: see CPRD data dictionary for further info"
			label variable data4 "Depends on enttype: see CPRD data dictionary for further info"
			label variable data5 "Depends on enttype: see CPRD data dictionary for further info"
			label variable data6 "Depends on enttype: see CPRD data dictionary for further info"
			label variable data7 "Depends on enttype: see CPRD data dictionary for further info"
			label variable data8 "Depends on enttype: see CPRD data dictionary for further info"
				
		* Sort on patient ID and eventdate
			
			sort patid eventdate_num
			
		* Compress data
		
			compress *
			
			save "$Rawdatadir\original sept 21\cohort 1\stata\Test_`disease'_`number'.dta", replace
		
		}
	
		use "$Rawdatadir\original sept 21\cohort 1\stata\Test_`disease'_01.dta", clear
		append using "$Rawdatadir\original sept 21\cohort 1\stata\Test_`disease'_02.dta"

		duplicates report
		duplicates tag, gen(tag)
		tab tag
		duplicates drop	
		count
		drop tag
	
		save "$Tempdatadir\All_`disease'_Test.dta", replace
	
	}
	
* Thyroid
	
	use "$Rawdatadir\original sept 21\cohort 1\stata\Test_thy_01.dta", clear

* Create numerical variables for eventdate and sysdate
		
	gen eventdate_num = date(eventdate, "DMY")
	format eventdate_num %td
			
	gen sysdate_num = date(sysdate, "DMY")
	format sysdate_num %td
		
* Label variables
			
	label variable patid "Patient ID"
	label variable eventdate "Date of therapy event - string"
	label variable eventdate_num "Date of therapy event - numerical"
	label variable sysdate "Date entered on Vision - string"
	label variable sysdate_num "Date entered on Vision - numerical"
	label variable consid "Consultation ID: linkage with consultation file when used with pracid"
	label variable constype "Consultation type: category of event"
	label variable medcode "CPRD code for medical term, selected by GP"
	label variable sctid "The mapped SNOMED CT concept ID"
	label variable sctdescid "SNOMED description ID"
	label variable sctexpression "SNOMED expression"
	label variable sctmaptype "SNOMED mapping type"
	label variable sctmapversion "SNOMED mapping version"
	label variable sctisindicative "SCT is indicative"
	label variable sctisassured "SCT is assured"
	label variable staffid "ID of staff entering data onto Vision, zero ==unknown"
	label variable enttype "Entity type: structure data area in Vision where data was entered"
	label variable data1 "Depends on enttype: see CPRD data dictionary for further info"
	label variable data2 "Depends on enttype: see CPRD data dictionary for further info"
	label variable data3 "Depends on enttype: see CPRD data dictionary for further info"
	label variable data4 "Depends on enttype: see CPRD data dictionary for further info"
	label variable data5 "Depends on enttype: see CPRD data dictionary for further info"
	label variable data6 "Depends on enttype: see CPRD data dictionary for further info"
	label variable data7 "Depends on enttype: see CPRD data dictionary for further info"
	label variable data8 "Depends on enttype: see CPRD data dictionary for further info"
				
* Sort on patient ID and eventdate
			
	sort patid eventdate_num
			
* Compress data
		
	compress *
			
	save "$Tempdatadir\All_thy_Test.dta", replace
	
* Now append all the Test files from each disease area
	
	use "$Tempdatadir\All_dep_Test.dta", clear
	append using "$Tempdatadir\All_dia_Test.dta"
	append using "$Tempdatadir\All_hyt_Test.dta"
	append using "$Tempdatadir\All_thy_Test.dta"
	
	duplicates report
	duplicates tag, gen(tag)
	tab tag
	duplicates drop	
	count
	drop tag
	
	save "$Datadir\formatted_cprd_data\All_Test.dta", replace	
	
********************************************************************************
	
* STAFF

	foreach disease in dep dia hyt thy {

	* Add variable labels, sort on staff ID, compress
	
		use "$Rawdatadir\original sept 21\cohort 1\stata\Staff_`disease'_01.dta", clear
		
	* Label variables
			
		label variable staffid "ID of staff member who entered the data"
		label variable gender "Staff's gender"
		label variable role "Role of the staff member who created the event (lookup ROL)"
				
	* Sort on staff id
			
		sort staffid
			
	* Compress data
		
		compress *
			
		save "$Tempdatadir\All_`disease'_Staff.dta", replace
	
	}
	
	use "$Tempdatadir\All_dep_Staff.dta", replace
	append using "$Tempdatadir\All_dia_Staff.dta"
	append using "$Tempdatadir\All_hyt_Staff.dta"
	append using "$Tempdatadir\All_thy_Staff.dta"
	
	duplicates report
	duplicates tag, gen(tag)
	tab tag
	duplicates drop	
	count
	drop tag
	
	save "$Datadir\formatted_cprd_data\All_Staff.dta", replace
	
********************************************************************************

* REFERRAL

	foreach disease in dep dia hyt thy {

	* Generate numerical date variables, add variable labels, sort data on patid and eventdate and compress

		use "$Rawdatadir\original sept 21\cohort 1\stata\Referral_`disease'_01.dta", clear

	* Create numerical variables for eventdate and sysdate
		
		gen eventdate_num = date(eventdate, "DMY")
		format eventdate_num %td
			
		gen sysdate_num = date(sysdate, "DMY")
		format sysdate_num %td
		
	* Label variables
			
		label variable patid "Patient ID"
		label variable eventdate "Date of therapy event - string"
		label variable eventdate_num "Date of therapy event - numerical"
		label variable sysdate "Date entered on Vision - string"
		label variable sysdate_num "Date entered on Vision - numerical"
		label variable consid "Consultation ID: linkage with consultation file when used with pracid"
		label variable constype "Consultation type: category of event"
		label variable medcode "CPRD code for medical term, selected by GP"
		label variable sctid "The mapped SNOMED CT concept ID"
		label variable sctdescid "SNOMED description ID"
		label variable sctexpression "SNOMED expression"
		label variable sctmaptype "SNOMED mapping type"
		label variable sctmapversion "SNOMED mapping version"
		label variable sctisindicative "SCT is indicative"
		label variable sctisassured "SCT is assured"
		label variable staffid "ID of staff entering data onto Vision, zero ==unknown"
		label variable source "Classification of source of referral, e.g. GP, Self"
		label variable nhsspec "Referral speciality according to the NHS classification"
		label variable fhsaspec "Referral speciality according to the Family Health Services Authority classification"
		label variable inpatient "Classification of type of referral, e.g. day case, in-patient"
		label variable attendance "Category describing whether referral event is first visit, follow-up, etc."
		label variable urgency "Classification of the urgency of the referral, e.g. routine, urgent"
				
	* Sort on patient ID and eventdate
			
		sort patid eventdate_num
			
	* Compress data
		
		compress *
			
		save "$Tempdatadir\All_`disease'_Referral.dta", replace
	
	}

	use "$Tempdatadir\All_dep_Referral.dta", replace
	append using "$Tempdatadir\All_dia_Referral.dta"
	append using "$Tempdatadir\All_hyt_Referral.dta"
	append using "$Tempdatadir\All_thy_Referral.dta"
	
	duplicates report
	duplicates tag, gen(tag)
	tab tag
	duplicates drop	
	count
	drop tag
	
	save "$Datadir\formatted_cprd_data\All_Referral.dta", replace
	
********************************************************************************

* PRACTICE

	foreach disease in dep dia hyt thy {

	* Generate numerical date variables, add variable labels, sort data on pracid 
	
		use "$Rawdatadir\original sept 21\cohort 1\stata\Practice_`disease'_01.dta", clear

	* Create numerical variables for eventdate and sysdate
		
		gen lcd_num = date(lcd, "DMY")
		format lcd_num %td
			
		gen uts_num = date(uts, "DMY")
		format uts_num %td
		
	* Label variables
			
		label variable pracid "Practice ID"
		label variable region "Region within the UK (lookup PRG)"
		label variable lcd "Date of last collection for the practice - string"
		label variable lcd_num "Date of last collection for the practice - numerical"
		label variable uts "Date at which practice data is deemed to be of research quality - string"
		label variable uts "Date at which practice data is deemed to be of research quality - numerical"
			
	* Sort on practice id
		
		sort pracid
			
		save "$Tempdatadir\All_`disease'_Practice.dta", replace	
		
	}
	
	use "$Tempdatadir\All_dep_Practice.dta", replace
	append using "$Tempdatadir\All_dia_Practice.dta"
	append using "$Tempdatadir\All_hyt_Practice.dta"
	append using "$Tempdatadir\All_thy_Practice.dta"
	
	duplicates report
	duplicates tag, gen(tag)
	tab tag
	duplicates drop	
	count
	drop tag
	
	save "$Datadir\formatted_cprd_data\All_Practice.dta", replace

********************************************************************************

* PATIENT

	foreach disease in dep dia hyt thy {

	* Generate numerical date variables, add variable labels, sort data on patid and compress

		use "$Rawdatadir\original sept 21\cohort 1\stata\Patient_`disease'_01.dta", clear

	* Create numerical variables for eventdate and sysdate
		
		gen chsdate_num = date(chsdate, "DMY")
		format chsdate_num %td
			
		gen frd_num = date(frd, "DMY")
		format frd_num %td
			
		gen crd_num = date(crd, "DMY")
		format crd_num %td
			
		gen tod_num = date(tod, "DMY")
		format tod_num %td
		
	* Label variables
			
		label variable patid "Patient ID"
		label variable vmid "Old VM ID for patient when practice used the VAMP system"
		label variable gender "Patient's gender"
		label variable yob "Patient's year of birth"
		label variable mob "Patient's month of birth"
		label variable marital "Patients current marital status (lookup MAR)"
		label variable famnum "Family ID"
		label variable chsreg "Patient registered with Child Health Surveillance"
		label variable chsdate "Date of registration with CHS - string"
		label variable chsdate_num "Date of registration with CHS - numerical"
		label variable prescr "Type of prescribing exception the patient has currently (medical, maternity)"
		label variable capsup "Level of capitation supplement the patient has currently (low, medium, high)"
		label variable frd "Date of patient's first registation with practice (important: see data spec for info)"
		label variable frd_num "Date of patient's first registration - numerical"
		label variable crd "Date the patients current registration with practice began (important: see data spec for info)"
		label variable crd_num "Date the patient's current registration with practice began - numerical"
		label variable regstat "Status of registration detailing gaps and temporary patients"
		label variable reggap "Number of days missing in the patients' registration details"
		label variable internal "Number of internal transfer out periods, in the patient's registration details"
		label variable tod "Date patient transferred out of practice, if relevant"
		label variable tod_num "Date patient tranferred out of practice - numerical"
		label variable toreason "Reason for patient transferring out of practice"
		label variable deathdate "Date of death of patient - derived using a CPRD algorithm"
		label variable accept "Flag to indicate whether patient has met certain quality standards"
			
	* Sort on practice id
		
		sort patid
		
	* Generate a flag showing which patient is in which cohort
	
		gen `disease' = 1
			
	* Compress
		
		compress *
			
		save "$Tempdatadir\All_`disease'_Patient.dta", replace
		
	}
	
	use "$Tempdatadir\All_dep_Patient.dta", replace
	merge 1:1 patid using "$Tempdatadir\All_dia_Patient.dta", nogen
	merge 1:1 patid using "$Tempdatadir\All_hyt_Patient.dta", nogen
	merge 1:1 patid using "$Tempdatadir\All_thy_Patient.dta", nogen
	
	foreach disease in dep dia hyt thy {
	    
		replace `disease' = 0 if `disease'==.
		
	}
	
	save "$Datadir\formatted_cprd_data\All_Patient.dta", replace
	
********************************************************************************
			
* IMMUNISATION

	foreach disease in dep dia hyt thy {

	* Generate numerical date variables, add variable labels, sort data on patid and compress

		use "$Rawdatadir\original sept 21\cohort 1\stata\Immunisation_`disease'_01.dta", clear		
 
	* Create numerical variables for eventdate and sysdate
		
		gen eventdate_num = date(eventdate, "DMY")
		format eventdate_num %td
			
		gen sysdate_num = date(sysdate, "DMY")
		format sysdate_num %td
			
	* Label variables
			
		label variable patid "Patient ID"
		label variable eventdate "Date of therapy event - string"
		label variable eventdate_num "Date of therapy event - numerical"
		label variable sysdate "Date entered on Vision - string"
		label variable sysdate_num "Date entered on Vision - numerical"
		label variable consid "Consultation ID: linkage with consultation file when used with pracid"
		label variable constype "Consultation type: category of event"
		label variable medcode "CPRD code for medical term, selected by GP"
		label variable sctid "The mapped SNOMED CT concept ID"
		label variable sctdescid "SNOMED description ID"
		label variable sctexpression "SNOMED expression"
		label variable sctmaptype "SNOMED mapping type"
		label variable sctmapversion "SNOMED mapping version"
		label variable sctisindicative "SCT is indicative"
		label variable sctisassured "SCT is assured"
		label variable staffid "ID of staff entering data onto Vision, zero ==unknown"
		label variable immstype "Individual components of an immunisation (e.g. Mumps, Rubella, Measles)"
		label variable stage "Stage of immunisation given"
		label variable status "Status of the immunisation (advised, given, refusal)"
		label variable compound "Immunisation compound administered, single or multi-component preparation"
		label variable source "Location where immunisation was administered"
		label variable reason "Reason for administering immunisation, e.g. routine measure"
		label variable method "Route of administration of the immunisation, e.g. oral, intramuscular"
		label variable batch "Immunisation batch number"
			
	* Sort on patient id and eventdate
	
		sort patid eventdate_num
			
	* Compress
		
		compress *
			
		save "$Tempdatadir\All_`disease'_Immunisation.dta", replace
		
	}

	use "$Tempdatadir\All_dep_Immunisation.dta", replace
	append using "$Tempdatadir\All_dia_Immunisation.dta"
	append using "$Tempdatadir\All_hyt_Immunisation.dta"
	append using "$Tempdatadir\All_thy_Immunisation.dta"
	
	duplicates report
	duplicates tag, gen(tag)
	tab tag
	duplicates drop	
	count
	drop tag
	
	save "$Datadir\formatted_cprd_data\All_Immunisation.dta", replace
	
********************************************************************************
	
* CONSULTATION

* Generate numerical date variables, add variable labels, sort data on patid and compress

* Depression

	foreach number in 01 02 03 04 05 {
	
			use "$Rawdatadir\original sept 21\cohort 1\stata\Consultation_dep_`number'.dta", clear		
 
		* Create numerical variables for eventdate and sysdate
		
			gen eventdate_num = date(eventdate, "DMY")
			format eventdate_num %td
			
			gen sysdate_num = date(sysdate, "DMY")
			format sysdate_num %td	
	
		* Label variables
			
			label variable patid "Patient ID"
			label variable eventdate "Date of therapy event - string"
			label variable eventdate_num "Date of therapy event - numerical"
			label variable sysdate "Date entered on Vision - string"
			label variable sysdate_num "Date entered on Vision - numerical"
			label variable consid "Consultation ID: linkage with consultation file when used with pracid"
			label variable constype "Consultation type: category of event"
			label variable staffid "ID of staff entering data onto Vision, zero ==unknown"
			label variable duration "Length of time between opening and closing consultation record"
			
		* Sort on patient id and eventdate
		
			sort patid eventdate_num
			
		* Compress
		
			compress *
			
			save "$Rawdatadir\original sept 21\cohort 1\stata\Consultation_dep_`number'.dta", replace		
	
	}	
	
	use "$Rawdatadir\original sept 21\cohort 1\stata\Consultation_dep_01.dta", clear
	append using "$Rawdatadir\original sept 21\cohort 1\stata\Consultation_dep_02.dta"
	append using "$Rawdatadir\original sept 21\cohort 1\stata\Consultation_dep_03.dta"
	append using "$Rawdatadir\original sept 21\cohort 1\stata\Consultation_dep_04.dta"
	append using "$Rawdatadir\original sept 21\cohort 1\stata\Consultation_dep_05.dta"
	
	duplicates drop	
	count
	
	save "$Tempdatadir\All_dep_Consultation.dta", replace	
	
* Diabete and hypertension

	foreach disease in dia hyt {
		foreach number in 01 02 {
	
			use "$Rawdatadir\original sept 21\cohort 1\stata\Consultation_`disease'_`number'.dta", clear		
 
		* Create numerical variables for eventdate and sysdate
		
			gen eventdate_num = date(eventdate, "DMY")
			format eventdate_num %td
			
			gen sysdate_num = date(sysdate, "DMY")
			format sysdate_num %td	
	
		* Label variables
			
			label variable patid "Patient ID"
			label variable eventdate "Date of therapy event - string"
			label variable eventdate_num "Date of therapy event - numerical"
			label variable sysdate "Date entered on Vision - string"
			label variable sysdate_num "Date entered on Vision - numerical"
			label variable consid "Consultation ID: linkage with consultation file when used with pracid"
			label variable constype "Consultation type: category of event"
			label variable staffid "ID of staff entering data onto Vision, zero ==unknown"
			label variable duration "Length of time between opening and closing consultation record"
			
		* Sort on patient id and eventdate
		
			sort patid eventdate_num
			
		* Compress
		
			compress *
			
			save "$Rawdatadir\original sept 21\cohort 1\stata\Consultation_`disease'_`number'.dta", replace		
	
		}	
	
		use "$Rawdatadir\original sept 21\cohort 1\stata\Consultation_`disease'_01.dta", clear
		append using "$Rawdatadir\original sept 21\cohort 1\stata\Consultation_`disease'_02.dta"
	
		duplicates drop	
		count
	
		save "$Tempdatadir\All_`disease'_Consultation.dta", replace
	
	}
	
* Thyroid

		use "$Rawdatadir\original sept 21\cohort 1\stata\Consultation_thy_01.dta", clear		
 
	* Create numerical variables for eventdate and sysdate
		
		gen eventdate_num = date(eventdate, "DMY")
		format eventdate_num %td
			
		gen sysdate_num = date(sysdate, "DMY")
		format sysdate_num %td	
	
	* Label variables
			
		label variable patid "Patient ID"
		label variable eventdate "Date of therapy event - string"
		label variable eventdate_num "Date of therapy event - numerical"
		label variable sysdate "Date entered on Vision - string"
		label variable sysdate_num "Date entered on Vision - numerical"
		label variable consid "Consultation ID: linkage with consultation file when used with pracid"
		label variable constype "Consultation type: category of event"
		label variable staffid "ID of staff entering data onto Vision, zero ==unknown"
		label variable duration "Length of time between opening and closing consultation record"
			
	* Sort on patient id and eventdate
		
		sort patid eventdate_num
			
	* Compress
		
		compress *
			
		save "$Tempdatadir\All_thy_Consultation.dta", replace
		
* All Consultations

	use "$Tempdatadir\All_dep_Consultation.dta", replace
	append using "$Tempdatadir\All_dia_Consultation.dta"
	append using "$Tempdatadir\All_hyt_Consultation.dta"
	append using "$Tempdatadir\All_thy_Consultation.dta"
	
	duplicates report
	duplicates tag, gen(tag)
	tab tag
	duplicates drop	
	count
	drop tag
	
	save "$Datadir\formatted_cprd_data\All_Consultation.dta", replace
	
	
********************************************************************************
	
* CLINICAL

* Depression

* Generate numerical date variables, add variable labels, sort data on patid and compress

	foreach number in 01 02 03 04 05 06 {
	
			use "$Rawdatadir\original sept 21\cohort 1\stata\Clinical_dep_`number'.dta", clear		
 
		* Create numerical variables for eventdate and sysdate
		
			gen eventdate_num = date(eventdate, "DMY")
			format eventdate_num %td
			
			gen sysdate_num = date(sysdate, "DMY")
			format sysdate_num %td	
	
		* Label variables
			
			label variable patid "Patient ID"
			label variable eventdate "Date of therapy event - string"
			label variable eventdate_num "Date of therapy event - numerical"
			label variable sysdate "Date entered on Vision - string"
			label variable sysdate_num "Date entered on Vision - numerical"
			label variable consid "Consultation ID: linkage with consultation file when used with pracid"
			label variable constype "Consultation type: category of event"
			label variable medcode "CPRD code for medical term, selected by GP"
			label variable sctid "The mapped SNOMED CT concept ID"
			label variable sctdescid "SNOMED description ID"
			label variable sctexpression "SNOMED expression"
			label variable sctmaptype "SNOMED mapping type"
			label variable sctmapversion "SNOMED mapping version"
			label variable sctisindicative "SCT is indicative"
			label variable sctisassured "SCT is assured"
			label variable staffid "ID of staff entering data onto Vision, zero ==unknown"
			label variable episode "Episode type for a specific clinical event (lookup EPI)"
			label variable enttype "Identifies representing the structured data area in Vision (lookup Entity)"
			label variable adid "Identified allowing additional info to be retrieved in combination with pracid"
			
		* Sort on patient id and eventdate
		
			sort patid eventdate_num
			
		* Compress
		
			compress *
			
			save "$Rawdatadir\original sept 21\cohort 1\stata\Clinical_dep_`number'.dta", replace		
	
	}
	
	use "$Rawdatadir\original sept 21\cohort 1\stata\Clinical_dep_01.dta", clear
	append using "$Rawdatadir\original sept 21\cohort 1\stata\Clinical_dep_02.dta"
	append using "$Rawdatadir\original sept 21\cohort 1\stata\Clinical_dep_03.dta"
	append using "$Rawdatadir\original sept 21\cohort 1\stata\Clinical_dep_04.dta"
	append using "$Rawdatadir\original sept 21\cohort 1\stata\Clinical_dep_05.dta"
	append using "$Rawdatadir\original sept 21\cohort 1\stata\Clinical_dep_06.dta"
	
	duplicates drop	
	count
	
	save "$Tempdatadir\All_dep_Clinical.dta", replace
	
* Diabetes and hypertension

	foreach disease in dia hyt {
			foreach number in 01 02 {
	
				use "$Rawdatadir\original sept 21\cohort 1\stata\Clinical_`disease'_`number'.dta", clear		
 
			* Create numerical variables for eventdate and sysdate
		
				gen eventdate_num = date(eventdate, "DMY")
				format eventdate_num %td
			
				gen sysdate_num = date(sysdate, "DMY")
				format sysdate_num %td	
	
			* Label variables
			
				label variable patid "Patient ID"
				label variable eventdate "Date of therapy event - string"
				label variable eventdate_num "Date of therapy event - numerical"
				label variable sysdate "Date entered on Vision - string"
				label variable sysdate_num "Date entered on Vision - numerical"
				label variable consid "Consultation ID: linkage with consultation file when used with pracid"
				label variable constype "Consultation type: category of event"
				label variable medcode "CPRD code for medical term, selected by GP"
				label variable sctid "The mapped SNOMED CT concept ID"
				label variable sctdescid "SNOMED description ID"
				label variable sctexpression "SNOMED expression"
				label variable sctmaptype "SNOMED mapping type"
				label variable sctmapversion "SNOMED mapping version"
				label variable sctisindicative "SCT is indicative"
				label variable sctisassured "SCT is assured"
				label variable staffid "ID of staff entering data onto Vision, zero ==unknown"
				label variable episode "Episode type for a specific clinical event (lookup EPI)"
				label variable enttype "Identifies representing the structured data area in Vision (lookup Entity)"
				label variable adid "Identified allowing additional info to be retrieved in combination with pracid"
				
			* Sort on patient id and eventdate
		
				sort patid eventdate_num
				
			* Compress
		
				compress *
			
				save "$Rawdatadir\original sept 21\cohort 1\stata\Clinical_`disease'_`number'.dta", replace		
	
			}
	
		use "$Rawdatadir\original sept 21\cohort 1\stata\Clinical_`disease'_01.dta", clear
		append using "$Rawdatadir\original sept 21\cohort 1\stata\Clinical_`disease'_02.dta"
	
		duplicates drop	
		count
	
		save "$Tempdatadir\All_`disease'_Clinical.dta", replace
	
	}
	
* Thyroid 

		use "$Rawdatadir\original sept 21\cohort 1\stata\Clinical_thy_01.dta", clear		
 
	* Create numerical variables for eventdate and sysdate
		
		gen eventdate_num = date(eventdate, "DMY")
		format eventdate_num %td
			
		gen sysdate_num = date(sysdate, "DMY")
		format sysdate_num %td	
	
	* Label variables
			
		label variable patid "Patient ID"
		label variable eventdate "Date of therapy event - string"
		label variable eventdate_num "Date of therapy event - numerical"
		label variable sysdate "Date entered on Vision - string"
		label variable sysdate_num "Date entered on Vision - numerical"
		label variable consid "Consultation ID: linkage with consultation file when used with pracid"
		label variable constype "Consultation type: category of event"
		label variable medcode "CPRD code for medical term, selected by GP"
		label variable sctid "The mapped SNOMED CT concept ID"
		label variable sctdescid "SNOMED description ID"
		label variable sctexpression "SNOMED expression"
		label variable sctmaptype "SNOMED mapping type"
		label variable sctmapversion "SNOMED mapping version"
		label variable sctisindicative "SCT is indicative"
		label variable sctisassured "SCT is assured"
		label variable staffid "ID of staff entering data onto Vision, zero ==unknown"
		label variable episode "Episode type for a specific clinical event (lookup EPI)"
		label variable enttype "Identifies representing the structured data area in Vision (lookup Entity)"
		label variable adid "Identified allowing additional info to be retrieved in combination with pracid"
			
	* Sort on patient id and eventdate
		
		sort patid eventdate_num
			
	* Compress
		
		compress *
			
		save "$Tempdatadir\All_thy_Clinical.dta", replace	
		
* All Clinical

	use "$Tempdatadir\All_dep_Clinical.dta", replace
	append using "$Tempdatadir\All_dia_Clinical.dta"
	append using "$Tempdatadir\All_hyt_Clinical.dta"
	append using "$Tempdatadir\All_thy_Clinical.dta"
	
	duplicates report
	duplicates tag, gen(tag)
	tab tag
	duplicates drop	
	count
	drop tag
	
	save "$Datadir\formatted_cprd_data\All_Clinical.dta", replace

********************************************************************************
	
* ADDITIONAL

	foreach disease in dep dia hyt thy {

	* Add variable labels, sort data on patid and compress
	
		use "$Rawdatadir\original sept 21\cohort 1\stata\Additional_`disease'_01.dta", clear		
 
	* Label variables
			
		label variable patid "Patient ID"
		label variable enttype "Identifies representing the structured data area in Vision (lookup Entity)"
		label variable adid "Identified allowing additional info to be retrieved in combination with pracid"
		label variable data1 "Depends on enttype (lookup Entity)"
		label variable data2 "Depends on enttype (lookup Entity)"
		label variable data3 "Depends on enttype (lookup Entity)"
		label variable data4 "Depends on enttype (lookup Entity)"
		label variable data5 "Depends on enttype (lookup Entity)"
		label variable data6 "Depends on enttype (lookup Entity)"
		label variable data7 "Depends on enttype (lookup Entity)"
		label variable data8 "Depends on enttype (lookup Entity)"
		label variable data9 "Depends on enttype (lookup Entity)"
		label variable data10 "Depends on enttype (lookup Entity)"
		label variable data11 "Depends on enttype (lookup Entity)"
		label variable data12 "Depends on enttype (lookup Entity)"

	* Sort on patient id and eventdate
		
		sort patid
			
	* Compress
		
		compress *
	
		save "$Tempdatadir\All_`disease'_Additional.dta", replace
	
	}
	
	use "$Tempdatadir\All_dep_Additional.dta", replace
	append using "$Tempdatadir\All_dia_Additional.dta"
	append using "$Tempdatadir\All_hyt_Additional.dta"
	append using "$Tempdatadir\All_thy_Additional.dta"
	
	duplicates report
	duplicates tag, gen(tag)
	tab tag
	duplicates drop	
	count
	drop tag
	
	save "$Datadir\formatted_cprd_data\All_Additional.dta", replace
	
********************************************************************************

	foreach file in Therapy Test Staff Referral Practice Patient Immunisation Consultation Clinical Additional {
	    
		use "$Tempdatadir\All_dep_`file'.dta", clear
		save "$Depdir\All_dep_`file'.dta", replace
		
	}
		
********************************************************************************

* Delete all unnecessary files

	foreach disease in dep dia hyt thy {
		foreach file in Therapy Test Staff Referral Practice Patient Immunisation Consultation Clinical Additional {
		
			erase "$Tempdatadir\All_`disease'_`file'.dta"
			
		}
		
	}
	
********************************************************************************

* Stop logging

	log close

********************************************************************************
