********************************************************************************

* This syntax routine pulls together all the pieces of Practice data provided by CPRD in the new data delivery ready for using with the old Practice data delivery - All_Practice as these data are small enough to use as one dataset (unlike Therapy)

* Author: Flo Martin (adapted from scripts by Hein Heuvelman)

* Date: 28/06/2023

********************************************************************************

* Datasets generated by this do-file

	* All Referral data for using in subsequent PhD projects
	
	* $Datadir\formatted_cprd_data\All_Practice.dta 

********************************************************************************

* Start logging

	log using "$Logdir\1_formatting\9_formatting practice.txt", replace
	
********************************************************************************

* Pull together pieces of data within each Patient chunk

	use "$Rawdatadir\redelivery may 23\primary care\Practice_01_0.dta", clear
	
	forvalues x=1/10 {	
		
		append using "$Rawdatadir\redelivery may 23\primary care\Practice_01_`x'.dta"
		
	}
	
	append using "$Cohortonedir\formatted_cprd_data\All_Practice.dta"
	count
	
	drop *_num
	
	* Create numerical variables for eventdate and sysdate
		
		gen lcd_num = date(lcd, "DMY")
		format lcd_num %td
			
		gen uts_num = date(uts, "DMY")
		format uts_num %td
		
	* Label variables
			
		label variable pracid "Practice ID"
		label variable region "Region within the UK (lookup PRG)"
		label variable lcd "Date of last collection for the practice - string"
		label variable lcd_num "Date of last collection for the practice - numerical"
		label variable uts "Date at which practice data is deemed to be of research quality - string"
		label variable uts "Date at which practice data is deemed to be of research quality - numerical"
			
	* Sort on practice id
		
	bysort pracid (lcd_num): egen seq=seq()
	tab seq
	
	keep if seq==1 // last collection date from the June build
	drop seq
		
	duplicates drop
	compress
		
	count
	
	save "$Datadir\formatted_cprd_data\All_Practice.dta", replace
	
********************************************************************************

* Stop logging

	log close
	
********************************************************************************
