
********************************************************************************

* Potential teratogen exposure before and during pregnancy - cancer medications, autoimmune condition treatments, antibiotics, painkillers etc.

* Author: Flo Martin

* Date: 04/05/2024

********************************************************************************

* Datasets generated by this do-file

*  - $Datadir\covariates\teratogen_preg_Rx.dta

********************************************************************************

  use "$Datadir\derived_data\pregnancy_cohort_final.dta", clear
	bysort patid: gen bign = _N
	summ bign // n = 14 max number of pregnancies
	local maxpreg = r(max)
	sort patid pregstart_num
	drop bign

	use "$Datadir\formatted_cprd_data\All_Therapy_reduced.dta", clear
	keep patid prodcode eventdate_num
		
		* Merge with prodcode
		merge m:1 prodcode using "$Tocheckdir\reduced_teratogens_to_check.dta", keep(3)
		
		* Keep if matched
		drop _merge
		sort patid

		save "$Tempdatadir\Rx_teratogen_all.dta", replace
		
		forvalues n=1/`maxpreg' {
			
			use "$Datadir\derived_data\pregnancy_cohort_final_`n'.dta", clear
			keep patid pregid pregstart_num 	
			
			*Merge with pregnancy register
			merge 1:m patid using "$Tempdatadir\Rx_teratogen_all.dta", keep(3)
			
			*Keep if matched
			drop _merge
			sort patid
			
			gen _dist= pregstart_num-eventdate_num
			keep if _dist<=0 & _dist>-365
			
			gen teratogen_prepreg=1
			
			keep patid pregid teratogen_prepreg class
			save "$Tempdatadir\prepreg_teratogen_`n'.dta", replace
		
		}
		
		forvalues n=1/`maxpreg' {
			
			use "$Datadir\derived_data\pregnancy_cohort_final_`n'.dta", clear
			keep patid pregid pregstart_num pregend_num	
			
			*Merge with pregnancy register
			merge 1:m patid using "$Tempdatadir\Rx_teratogen_all.dta", keep(3)
			
			*Keep if matched
			drop _merge
			sort patid
			
			keep if eventdate_num>=pregstart_num & eventdate_num<pregend_
			
			gen teratogen_preg=1
			
			keep patid pregid teratogen_preg class
			save "$Tempdatadir\preg_teratogen_`n'.dta", replace
		
		}
		
	* Teratogens pre-pregnancy
	
	use "$Tempdatadir\prepreg_teratogen_1.dta", clear
	forvalues n=2/`maxpreg' {
		
		append using "$Tempdatadir\prepreg_teratogen_`n'.dta"
	
	}
	
	duplicates drop
	
	bysort patid pregid: egen _presseq=seq()
	tab _presseq
	
	reshape wide teratogen_prepreg class, i(patid pregid) j(_presseq)
	
	merge 1:1 patid pregid using "$Datadir\derived_data\pregnancy_cohort_final.dta", nogen keep(2 3)
	
	foreach x in ace heart arbs mh adhd cancer immunosup ra hormone thyroid emesis acne antibiotic anticoag nsaid {
		
		gen prepreg_`x'=.
	
	}
	
	replace prepreg_ace = 1 if class1==1 | class2==1 | class3==1 | class4==1 | class5==1
	replace prepreg_heart = 1 if class1==2 | class2==2 | class3==2 | class4==2 | class5==2
	replace prepreg_arbs = 1 if class1==3 | class2==3 | class3==3 | class4==3 | class5==3
	replace prepreg_mh = 1 if class1==4 | class2==4 | class3==4 | class4==4 | class5==4
	replace prepreg_adhd = 1 if class1==5 | class2==5 | class3==5 | class4==5 | class5==5
	replace prepreg_cancer = 1 if class1==6 | class2==6 | class3==6 | class4==6 | class5==6
	replace prepreg_immunosup = 1 if class1==7 | class2==7 | class3==7 | class4==7 | class5==7
	replace prepreg_ra = 1 if class1==8 | class2==8 | class3==8 | class4==8 | class5==8
	replace prepreg_hormone = 1 if class1==9 | class2==9 | class3==9 | class4==9 | class5==9
	replace prepreg_thyroid = 1 if class1==10 | class2==10 | class3==10 | class4==10 | class5==10
	replace prepreg_emesis = 1 if class1==11 | class2==11 | class3==11 | class4==11 | class5==11
	replace prepreg_acne = 1 if class1==12 | class2==12 | class3==12 | class4==12 | class5==12
	replace prepreg_antibiotic = 1 if class1==13 | class2==13 | class3==13 | class4==13 | class5==13
	replace prepreg_anticoag = 1 if class1==14 | class2==14 | class3==14 | class4==14 | class5==14
	replace prepreg_nsaid = 1 if class1==15 | class2==15 | class3==15 | class4==15 | class5==15
	
	foreach x in ace heart arbs mh adhd cancer immunosup ra hormone thyroid emesis acne antibiotic anticoag nsaid {
		
		replace prepreg_`x'=0 if prepreg_`x'==.
	
	}
	
	gen teratogen_prepreg = 1 if teratogen_prepreg1==1 | teratogen_prepreg2==1 | teratogen_prepreg3==1 | teratogen_prepreg4==1 | teratogen_prepreg5==1
	replace teratogen_prepreg = 0 if teratogen_prepreg==.
	
	keep patid pregid teratogen_prepreg prepreg_ace prepreg_heart prepreg_arbs prepreg_mh prepreg_adhd prepreg_cancer prepreg_immunosup prepreg_ra prepreg_hormone prepreg_thyroid prepreg_emesis prepreg_acne prepreg_antibiotic prepreg_anticoag prepreg_nsaid
	
	save "$Datadir\covariates\teratogen_prepreg_Rx.dta", replace
	
	* Teratogens during pregnancy
	
	use "$Tempdatadir\preg_teratogen_1.dta", clear
	forvalues n=2/`maxpreg' {
		
		append using "$Tempdatadir\preg_teratogen_`n'.dta"
	
	}
	
	duplicates drop
	
	bysort patid pregid: egen _presseq=seq()
	tab _presseq
	
	reshape wide teratogen_preg class, i(patid pregid) j(_presseq)
	
	merge 1:1 patid pregid using "$Datadir\derived_data\pregnancy_cohort_final.dta", nogen keep(2 3)
	
	foreach x in ace heart arbs mh adhd cancer immunosup ra hormone thyroid emesis acne antibiotic anticoag nsaid {
		
		gen preg_`x'=.
	
	}
	
	replace preg_ace = 1 if class1==1 | class2==1 | class3==1 | class4==1
	replace preg_heart = 1 if class1==2 | class2==2 | class3==2 | class4==2
	replace preg_arbs = 1 if class1==3 | class2==3 | class3==3 | class4==3
	replace preg_mh = 1 if class1==4 | class2==4 | class3==4 | class4==4
	replace preg_adhd = 1 if class1==5 | class2==5 | class3==5 | class4==5
	replace preg_cancer = 1 if class1==6 | class2==6 | class3==6 | class4==6
	replace preg_immunosup = 1 if class1==7 | class2==7 | class3==7 | class4==7
	replace preg_ra = 1 if class1==8 | class2==8 | class3==8 | class4==8
	replace preg_hormone = 1 if class1==9 | class2==9 | class3==9 | class4==9
	replace preg_thyroid = 1 if class1==10 | class2==10 | class3==10 | class4==10
	replace preg_emesis = 1 if class1==11 | class2==11 | class3==11 | class4==11
	replace preg_acne = 1 if class1==12 | class2==12 | class3==12 | class4==12
	replace preg_antibiotic = 1 if class1==13 | class2==13 | class3==13 | class4==13
	replace preg_anticoag = 1 if class1==14 | class2==14 | class3==14 | class4==14
	replace preg_nsaid = 1 if class1==15 | class2==15 | class3==15 | class4==15
	
	foreach x in ace heart arbs mh adhd cancer immunosup ra hormone thyroid emesis acne antibiotic anticoag nsaid {
		
		replace preg_`x'=0 if preg_`x'==.
	
	}
	
	gen teratogen_preg = 1 if teratogen_preg1==1 | teratogen_preg2==1 | teratogen_preg3==1 | teratogen_preg4==1
	replace teratogen_preg = 0 if teratogen_preg==.
	
	keep patid pregid teratogen_preg preg_ace preg_heart preg_arbs preg_mh preg_adhd preg_cancer preg_immunosup preg_ra preg_hormone preg_thyroid preg_emesis preg_acne preg_antibiotic preg_anticoag preg_nsaid
	
	save "$Datadir\covariates\teratogen_preg_Rx.dta", replace

********************************************************************************
