*******************************************************************************

* Illicit drug use derivation

* Author: Paul Madley-Dowd (adapted by Flo Martin)

* Date: 23/09/2022

*******************************************************************************

* Datasets generated by this do-file

*  - $Datadir\covariates\illicitdruguse.dta

*******************************************************************************

	use "$Datadir\derived_data\pregnancy_cohort_final.dta", clear
	bysort patid: gen bign = _N
	summ bign // n = 14 max number of pregnancies
	local maxpreg = r(max)
	sort patid pregstart_num
	drop bign

/* Read codes for illicit drug use from Clinical

	forvalues x=0/11 {

		use "$Datadir\formatted_cprd_data\Clinical_`x'.dta", clear
		keep patid medcode eventdate_num
		merge m:1 medcode using "$Codesdir\Readcode_Illicitdruguse_signed_off_DR.dta", keep(3) nogen
		keep patid eventdate_num
		save "$Tempdatadir\all_illicit_drug_Read_Clin_`x'.dta", replace
		
	}
	
* Read codes for illicit drug use from Referral
	
	use "$Datadir\formatted_cprd_data\All_Referral.dta", clear
	keep patid medcode eventdate_num
	merge m:1 medcode using "$Codesdir\Readcode_Illicitdruguse_signed_off_DR.dta", keep(3) nogen
	keep patid eventdate_num
	save "$Tempdatadir\all_illicit_drug_Read_Ref.dta", replace
	
* Append	
	
	use "$Tempdatadir\all_illicit_drug_Read_Ref.dta", clear
	
	forvalues x=0/11 {
		
		append using "$Tempdatadir\all_illicit_drug_Read_Clin_`x'.dta"
		
	}
	
	save "$Tempdatadir\all_illicit_drug_Read.dta", replace
	
* Evidence of illicit drug use during pregnancy

	forvalues x = 1/`maxpreg' {
		
		use "$Datadir\derived_data\pregnancy_cohort_final_`x'.dta", clear 
		keep patid pregid pregstart_num pregend_num
		merge 1:m patid using "$Tempdatadir\all_illicit_drug_Read.dta", keep(3) nogen	
		keep if eventdate_num>=pregstart_num & eventdate_num<pregend_num 
	
		if _N >0 {
		
			gen illicit_preg = 1
			keep patid pregid illicit_preg
			
			duplicates drop

		}
		
		else if _N==0 {
			
			keep patid pregid
			gen illicit_preg =.
		
		}
	
		keep patid pregid illicit_preg
		save "$Tempdatadir\illicitdrug_preg_`x'.dta", replace

	}

	use "$Tempdatadir\illicitdrug_preg_1.dta", clear

	forvalues x = 2/`maxpreg' {
	
		append using "$Tempdatadir\illicitdrug_preg_`x'.dta"

	}

	merge 1:1 patid pregid using "$Datadir\derived_data\pregnancy_cohort_final.dta", nogen
	replace illicit_preg = 0 if illicit_preg==. 
	keep patid pregid illicit_preg

	sort patid
	compress
	save "$Tempdatadir\illicitdrug_preg_read.dta", replace
	
*******************************************************************************

* Prescriptions for illicit drug use (e.g. methadone) during pregnancy

	use "$Datadir\formatted_cprd_data\All_Therapy_reduced.dta", clear
	keep patid prodcode eventdate_num
	merge m:1 prodcode using "$Codesdir\Prescriptions_OST_reviewed_DR.dta", keep(3) nogen
	keep patid eventdate_num
	save "$Tempdatadir\all_OST_prescription.dta", replace
	
	forvalues x = 1/`maxpreg' {
	
		use "$Datadir\derived_data\pregnancy_cohort_final_`x'.dta", clear 
		keep patid pregid pregstart_num pregend_num
		merge 1:m patid using "$Tempdatadir\all_OST_prescription.dta", keep(3) nogen	
		keep if eventdate_num>=pregstart_num & eventdate_num<pregend_num
	
		if _N >0 {
		
			gen pxn_illicit_preg = 1
			keep patid pregid pxn_illicit_preg
			
			duplicates drop
	
		}
		
		else if _N==0 {
			
			keep patid pregid
			gen pxn_illicit_preg =.
		
		}
	
		keep patid pregid pxn_illicit_preg
		save "$Tempdatadir\OSTpresc_preg_`x'.dta", replace

	}

	use "$Tempdatadir\OSTpresc_preg_1.dta", clear
	
	forvalues x = 2/`maxpreg' {
	
		append using "$Tempdatadir\OSTpresc_preg_`x'.dta"

	}

	merge 1:1 patid pregid using "$Datadir\derived_data\pregnancy_cohort_final.dta", nogen
	replace pxn_illicit_preg = 0 if pxn_illicit_preg==. 
	keep patid pregid pxn_illicit_preg

	sort patid
	compress
	save "$Tempdatadir\OSTpresc_preg.dta", replace

* Join datasets

	use "$Tempdatadir\illicitdrug_preg_read.dta", clear
	merge 1:1 patid pregid using "$Tempdatadir\OSTpresc_preg.dta", nogen

	egen illicitdrug_preg = rowmax(illicit_preg pxn_illicit_preg) 
	keep patid pregid illicitdrug_preg

	label variable illicitdrug_preg "Evidence of illicit drug use in pregnancy"

	save "$Datadir\covariates\illicitdruguse_preg.dta", replace

*******************************************************************************

* Evidence of illicit drug use 12 months before pregnancy

	forvalues x = 1/`maxpreg' {
		
		use "$Datadir\derived_data\pregnancy_cohort_final_`x'.dta", clear 
		keep patid pregid pregstart_num pregend_num
		merge 1:m patid using "$Tempdatadir\all_illicit_drug_Read.dta", keep(3) nogen	
		keep if eventdate_num<pregstart_num & eventdate_num>=pregstart_num-365 
	
		if _N >0 {
		
			gen illicit_12mo = 1
			keep patid pregid illicit_12mo
			
			duplicates drop

		}
		
		else if _N==0 {
			
			keep patid pregid
			gen illicit_12mo =.
		
		}
	
		keep patid pregid illicit_12mo
		save "$Tempdatadir\illicitdrug_12mo_`x'.dta", replace

	}

	use "$Tempdatadir\illicitdrug_12mo_1.dta", clear

	forvalues x = 2/`maxpreg' {
	
		append using "$Tempdatadir\illicitdrug_12mo_`x'.dta"

	}

	merge 1:1 patid pregid using "$Datadir\derived_data\pregnancy_cohort_final.dta", nogen
	replace illicit_12mo = 0 if illicit_12mo==. 
	keep patid pregid illicit_12mo

	sort patid
	compress
	save "$Tempdatadir\illicitdrug_12mo_read.dta", replace*/
	
*******************************************************************************

* Prescriptions for illicit drug use (e.g. methadone) 12 months before pregnancy
	
	forvalues x = 1/`maxpreg' {
	
		use "$Datadir\derived_data\pregnancy_cohort_final_`x'.dta", clear 
		keep patid pregid pregstart_num pregend_num
		merge 1:m patid using "$Tempdatadir\all_OST_prescription.dta", keep(3) nogen	
		keep if eventdate_num<pregstart_num & eventdate_num>=pregstart_num-365 
	
		if _N >0 {
		
			gen pxn_illicit_12mo = 1
			keep patid pregid pxn_illicit_12mo
			
			duplicates drop
	
		}
		
		else if _N==0 {
			
			keep patid pregid
			gen pxn_illicit_12mo =.
		
		}
	
		keep patid pregid pxn_illicit_12mo
		save "$Tempdatadir\OSTpresc_12mo_`x'.dta", replace

	}

	use "$Tempdatadir\OSTpresc_12mo_1.dta", clear
	
	forvalues x = 2/`maxpreg' {
	
		append using "$Tempdatadir\OSTpresc_12mo_`x'.dta"

	}

	merge 1:1 patid pregid using "$Datadir\derived_data\pregnancy_cohort_final.dta", nogen
	replace pxn_illicit_12mo = 0 if pxn_illicit_12mo==. 
	keep patid pregid pxn_illicit_12mo

	sort patid
	compress
	save "$Tempdatadir\OSTpresc_12mo.dta", replace

* Join datasets

	use "$Tempdatadir\illicitdrug_12mo_read.dta", clear
	merge 1:1 patid pregid using "$Tempdatadir\OSTpresc_12mo.dta", nogen

	egen illicitdrug_12mo = rowmax(illicit_12mo pxn_illicit_12mo) 
	keep patid pregid illicitdrug_12mo

	label variable illicitdrug_12mo "Evidence of illicit drug use pre-pregnancy"

	save "$Datadir\covariates\illicitdruguse_12mo.dta", replace
	
*******************************************************************************

* Join pregnancy and 12 months pre-pregnancy

	use "$Datadir\covariates\illicitdruguse_12mo.dta", clear
	merge 1:1 patid pregid using "$Datadir\covariates\illicitdruguse_preg.dta", nogen
	
	save "$Datadir\covariates\illicitdruguse.dta", replace

*******************************************************************************

* Delete unnecessary datasets

	forvalues x=0/11 {
	
		erase "$Tempdatadir\all_illicit_drug_Read_Clin_`x'.dta"
		
	}
	
	erase "$Tempdatadir\all_illicit_drug_Read_Ref.dta"

	foreach n in preg 12mo {
		forvalues x=1/`maxpreg' {
		
			erase "$Tempdatadir\illicitdrug_`n'_`x'.dta"
			erase "$Tempdatadir\OSTpresc_`n'_`x'.dta"
		
		}
	}
	
	foreach n in preg 12mo {		
		
		erase "$Tempdatadir\illicitdrug_`n'_read.dta"
		erase "$Tempdatadir\OSTpresc_`n'.dta"
		
	}

*******************************************************************************
